### ISSUE TITLE
Test "ClearNetPeerExchangeServiceTest > test_peerExchange()" fails

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq2#119]
Run: `./gradlew build`

```
> Task :network:test

ClearNetPeerExchangeServiceTest > test_peerExchange() FAILED
    java.util.concurrent.CompletionException at ClearNetPeerExchangeServiceTest.java:31
        Caused by: java.net.BindException at ClearNetPeerExchangeServiceTest.java:31
14:07:07.537 ERROR [RateLimitedPersistenceClient-shutdownHook-MockAuthenticatedTextPayload] b.p.Persistence: Error at read for /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthenticatedTextPayload msg: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthenticatedTextPayload15988687740170779282.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthenticatedTextPayload java.io.IOException: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthenticatedTextPayload15988687740170779282.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthenticatedTextPayload
        at bisq.common.util.FileUtils.renameFile(FileUtils.java:277)
        at bisq.persistence.Persistence.persist(Persistence.java:117)
        at bisq.persistence.RateLimitedPersistenceClient.persistOnShutdown(RateLimitedPersistenceClient.java:71)
        at bisq.persistence.RateLimitedPersistenceClient.lambda$new$0(RateLimitedPersistenceClient.java:44)
        at java.base/java.lang.Thread.run(Thread.java:831)

java.io.IOException: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthenticatedTextPayload15988687740170779282.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthenticatedTextPayload
        at bisq.common.util.FileUtils.renameFile(FileUtils.java:277)
        at bisq.persistence.Persistence.persist(Persistence.java:117)
        at bisq.persistence.RateLimitedPersistenceClient.persistOnShutdown(RateLimitedPersistenceClient.java:71)
        at bisq.persistence.RateLimitedPersistenceClient.lambda$new$0(RateLimitedPersistenceClient.java:44)
        at java.base/java.lang.Thread.run(Thread.java:831)
14:07:07.537 ERROR [RateLimitedPersistenceClient-shutdownHook-MockAuthenticatedTextPayload] b.p.Persistence: Error at read for /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthenticatedTextPayload msg: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthenticatedTextPayload11454644664657696925.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthenticatedTextPayload java.io.IOException: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthenticatedTextPayload11454644664657696925.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthenticatedTextPayload
        at bisq.common.util.FileUtils.renameFile(FileUtils.java:277)
        at bisq.persistence.Persistence.persist(Persistence.java:117)
        at bisq.persistence.RateLimitedPersistenceClient.persistOnShutdown(RateLimitedPersistenceClient.java:71)
        at bisq.persistence.RateLimitedPersistenceClient.lambda$new$0(RateLimitedPersistenceClient.java:44)
        at java.base/java.lang.Thread.run(Thread.java:831)

java.io.IOException: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthenticatedTextPayload11454644664657696925.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthenticatedTextPayload
        at bisq.common.util.FileUtils.renameFile(FileUtils.java:277)
        at bisq.persistence.Persistence.persist(Persistence.java:117)
        at bisq.persistence.RateLimitedPersistenceClient.persistOnShutdown(RateLimitedPersistenceClient.java:71)
        at bisq.persistence.RateLimitedPersistenceClient.lambda$new$0(RateLimitedPersistenceClient.java:44)
        at java.base/java.lang.Thread.run(Thread.java:831)
14:07:07.537 ERROR [RateLimitedPersistenceClient-shutdownHook-MockAuthorizedPayload] b.p.Persistence: Error at read for /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthorizedPayload msg: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthorizedPayload15267026796255847209.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthorizedPayload java.io.IOException: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthorizedPayload15267026796255847209.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthorizedPayload
        at bisq.common.util.FileUtils.renameFile(FileUtils.java:277)
        at bisq.persistence.Persistence.persist(Persistence.java:117)
        at bisq.persistence.RateLimitedPersistenceClient.persistOnShutdown(RateLimitedPersistenceClient.java:71)
        at bisq.persistence.RateLimitedPersistenceClient.lambda$new$0(RateLimitedPersistenceClient.java:44)
        at java.base/java.lang.Thread.run(Thread.java:831)

java.io.IOException: Failed to rename /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/temp_MockAuthorizedPayload15267026796255847209.tmp to /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/MockAuthorizedPayload
        at bisq.common.util.FileUtils.renameFile(FileUtils.java:277)
        at bisq.persistence.Persistence.persist(Persistence.java:117)
        at bisq.persistence.RateLimitedPersistenceClient.persistOnShutdown(RateLimitedPersistenceClient.java:71)
        at bisq.persistence.RateLimitedPersistenceClient.lambda$new$0(RateLimitedPersistenceClient.java:44)
        at java.base/java.lang.Thread.run(Thread.java:831)
14:07:07.538 ERROR [RateLimitedPersistenceClient-shutdownHook-MockAuthenticatedTextPayload] b.p.Persistence: FileUtils.backupCorruptedFile failed: Could not make dir /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/corruptedFilesAtWrite java.io.IOException: Could not make dir /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/corruptedFilesAtWrite
        at bisq.common.util.FileUtils.makeDirs(FileUtils.java:160)
        at bisq.common.util.FileUtils.backupCorruptedFile(FileUtils.java:285)
        at bisq.persistence.Persistence.persist(Persistence.java:124)
        at bisq.persistence.RateLimitedPersistenceClient.persistOnShutdown(RateLimitedPersistenceClient.java:71)
        at bisq.persistence.RateLimitedPersistenceClient.lambda$new$0(RateLimitedPersistenceClient.java:44)
        at java.base/java.lang.Thread.run(Thread.java:831)

java.io.IOException: Could not make dir /home/user/.local/share/bisq_StorageTest/db/network/AuthenticatedDataStore/corruptedFilesAtWrite
        at bisq.common.util.FileUtils.makeDirs(FileUtils.java:160)
        at bisq.common.util.FileUtils.backupCorruptedFile(FileUtils.java:285)
        at bisq.persistence.Persistence.persist(Persistence.java:124)
        at bisq.persistence.RateLimitedPersistenceClient.persistOnShutdown(RateLimitedPersistenceClient.java:71)
        at bisq.persistence.RateLimitedPersistenceClient.lambda$new$0(RateLimitedPersistenceClient.java:44)
        at java.base/java.lang.Thread.run(Thread.java:831)

5 tests completed, 1 failed

> Task :network:test FAILED

FAILURE: Build failed with an exception.
```

**Comment by chimp1984** [comment]
Seems to be an issue on Qubes. On OSX it works. I guess on Linux as well

**Comment by alvasw** [comment]
This was probably a bug on my side. Works now!
