### ISSUE TITLE
NoClassDefFoundError on javafx MediaView when clicking "Watch video" on Apple Silicon Mac

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq2#1695]
Environment:

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.6.3
------------------------------------------------------------

Build time:   2023-10-04 15:59:47 UTC
Revision:     1694251d59e0d4752d547e1fd5b5020b798a7e71

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Oracle Corporation 17.0.7+8-LTS-224)
OS:           Mac OS X 13.5.2 aarch64
```

Repro steps:

1. Build and run from latest `main` (`ff4cd1a08` at time of writing): `./gradlew :desktop:desktop-app:run`
2. Click through EUA and icon creation screens
3. Click 'Enter Bisq Easy'
4. Click 'Watch video'
5. Observe error modal popping up with the following stack trace:

```
Feb-26 10:08:08.072 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.NoClassDefFoundError: javafx/scene/media/MediaView
	at bisq.desktop.main.content.bisq_easy.onboarding.video.BisqEasyVideoController.<init>(BisqEasyVideoController.java:38)
	at bisq.desktop.overlay.OverlayController.createController(OverlayController.java:148)
	at bisq.desktop.common.view.NavigationController.findController(NavigationController.java:137)
	at bisq.desktop.common.view.NavigationController.processNavigationTarget(NavigationController.java:48)
	at bisq.desktop.common.view.Navigation.lambda$navigateTo$1(Navigation.java:66)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.common.view.Navigation.lambda$navigateTo$2(Navigation.java:66)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at bisq.desktop.common.view.Navigation.navigateTo(Navigation.java:64)
	at bisq.desktop.main.content.bisq_easy.onboarding.BisqEasyOnboardingController.onPlayVideo(BisqEasyOnboardingController.java:70)
	[...]
```

I haven't looked deeper, but this feels reminiscent of the frequent problems that have been had in the past around JavaFX on Silicon Macs. I asked another contributor who is running Windows and they said they do not experience this issue.

**Comment by HenrikJannsen** [comment]
Any dev with a Apple Silicon who can work on that?
