### ISSUE TITLE
IllegalAccessError on javafx VirtualScrollBar when clicking "Open offerbook" on Apple Silicon Mac

### ISSUE THREAD

**Issue by cbeams** [bisq-network/bisq2#1697]
Environment:
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.6.3
------------------------------------------------------------

Build time:   2023-10-04 15:59:47 UTC
Revision:     1694251d59e0d4752d547e1fd5b5020b798a7e71

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Oracle Corporation 17.0.7+8-LTS-224)
OS:           Mac OS X 13.5.2 aarch64
```

Repro steps:

1. Build and run from latest `main` (`ff4cd1a08` as of this writing): `./gradlew :desktop:desktop-app:run`
2. Click through terms and conditions and icon creation
3. Click "Enter Bisq Easy"
4. Click "Open offerbook"
5. Observe error modal popping up with the following stack trace:

```
Feb-26 12:25:00.222 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.IllegalAccessError: class bisq.desktop.components.list_view.ListViewUtil (in unnamed module @0x5b8dfcc1) cannot access class com.sun.javafx.scene.control.VirtualScrollBar (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control to unnamed module @0x5b8dfcc1
	at bisq.desktop.components.list_view.ListViewUtil.findScrollbar(ListViewUtil.java:18)
	at bisq.desktop.components.list_view.ListViewUtil.findScrollbarAsync(ListViewUtil.java:25)
	at bisq.desktop.main.content.components.chatMessages.ChatMessagesListView$View.onViewAttached(ChatMessagesListView.java:700)
	at bisq.desktop.common.view.View.onViewAttachedInternal(View.java:98)
	at bisq.desktop.common.view.View.onViewAttachedPrivate(View.java:93)
	at bisq.desktop.common.view.View.handleSceneChange(View.java:54)
	at bisq.desktop.common.view.View.lambda$new$0(View.java:46)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.graphics/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1046)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1097)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:772)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1068)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1135)
	[...]
```

6. Click "Close" on the error modal and obseve that it pops up again with a similar stack trace, this time from `ChatMessagesListView` instead of `ListViewUtil`, but due to the same underlying problem of the javafx `VirtualScrollBar` being inaccessible:

```
Feb-26 12:26:48.652 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.IllegalAccessError: class bisq.desktop.main.content.components.chatMessages.ChatMessagesListView$View (in unnamed module @0x5b8dfcc1) cannot access class com.sun.javafx.scene.control.VirtualScrollBar (in module javafx.controls) because module javafx.controls does not export com.sun.javafx.scene.control to unnamed module @0x5b8dfcc1
	at bisq.desktop.main.content.components.chatMessages.ChatMessagesListView$View.onViewDetached(ChatMessagesListView.java:757)
	at bisq.desktop.common.view.View.onViewDetachedInternal(View.java:102)
	at bisq.desktop.common.view.View.onViewDetachedPrivate(View.java:86)
	at bisq.desktop.common.view.View.handleSceneChange(View.java:68)
	at bisq.desktop.common.view.View.lambda$new$0(View.java:46)
	[...]
```

The errors are fatal, in that the user cannot get past them and that the app must be shut down, and when restarting, the app re-enters the same error state.

Like with #1695, this looks like more of the familiar issues around javafx on Apple Silicon.

**Comment by cbeams** [comment]
Note that this issue is currently blocking progress on #1620 because I cannot create offers (to set up the series of screenshots) until it is fixed.

**Comment by HenrikJannsen** [comment]
Any dev with a Apple Silicon who can work on that?

**Comment by HenrikJannsen** [comment]
I think that patch should catch the exception (I cannot test it as I dont have Apple Silicon):
Of course it does not fix the methods functionality...

```
Index: apps/desktop/desktop/src/main/java/bisq/desktop/components/list_view/ListViewUtil.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/apps/desktop/desktop/src/main/java/bisq/desktop/components/list_view/ListViewUtil.java b/apps/desktop/desktop/src/main/java/bisq/desktop/components/list_view/ListViewUtil.java
--- a/apps/desktop/desktop/src/main/java/bisq/desktop/components/list_view/ListViewUtil.java	(revision 826ad586e27de22829c8ea15d7b2ad3764197620)
+++ b/apps/desktop/desktop/src/main/java/bisq/desktop/components/list_view/ListViewUtil.java	(date 1709027634752)
@@ -15,7 +15,14 @@
     // We need to lookup VirtualScrollBar not ScrollBar, as ScrollBar would return any of the parents scrollbars.
     public static Optional<VirtualScrollBar> findScrollbar(ListView<?> listView, Orientation orientation) {
         return listView.lookupAll("VirtualScrollBar").stream()
-                .filter(node -> node instanceof VirtualScrollBar)
+                .filter(node -> {
+                    try {
+                        return node instanceof VirtualScrollBar;
+                    } catch (IllegalAccessError e) {
+                        log.warn("Access to VirtualScrollBar failed", e);
+                        return false;
+                    }
+                })
                 .map(node -> (VirtualScrollBar) node)
                 .filter(scrollBar -> scrollBar.getOrientation().equals(orientation))
                 .findFirst();
```
