### ISSUE TITLE
Fix startup issues of Tor

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1798]
Tor setup sometimes hangs specially at first time using Bisq2.

**Comment by lucasbalieiro** [comment]
Hi Guys,

it is my first time running the application and I think i get the issue you are presenting here.

Looking at the logs, I get this:


`mar.-17 15:50:59.212 [NetworkService.network-IO-pool-0] ERROR b.d.DesktopApplicationService: Initializing applicationService failed java.util.concurrent.CompletionException: bisq.tor.controller.exceptions.TorBootstrapFailedException: Tor bootstrap timout triggered.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: bisq.tor.controller.exceptions.TorBootstrapFailedException: Tor bootstrap timout triggered.
	at bisq.tor.controller.NativeTorController.waitUntilBootstrapped(NativeTorController.java:146)
	at bisq.tor.TorService.initialize(TorService.java:99)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:133)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 common frames omitted`
	
 Another thing that I notice, every time that I run the application it goes a bit further in the Bootstrap %.

first stoped with 3%, then 6%, 12.50%, 12.75%

Hope that it helps.
