### ISSUE TITLE
[Bug] Can't take Bisq Easy trade (mediator related?!)

### ISSUE THREAD

**Issue by RequestPrivacy** [bisq-network/bisq2#1815]
Tried to take a trade and specified 'Trade amount', 'Payment method' and 'Review Trade' but once you hit 'Confirm take offer' one gets following exception:

```java
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at bisq.support.mediation.MediationRequestService.selectMediator(MediationRequestService.java:151)
	at bisq.support.mediation.MediationRequestService.selectMediator(MediationRequestService.java:132)
	at bisq.desktop.main.content.bisq_easy.take_offer.review.TakeOfferReviewController.takeOffer(TakeOfferReviewController.java:196)
	at bisq.desktop.main....
```

**Comment by RequestPrivacy** [comment]
Tried with a different account that has a certain reputation and it worked. Not sure if related.

**Comment by HenrikJannsen** [comment]
Yes that was a bug. Its fixed here. Will be out with next release v2.0.2.

The bug happens if the hash of the 2 peers profileIds result in a negative integer. Which is unfortunately a 50% chance ;-(. 

Yes if you create another profile as taker you get another hash and with some luck the resulting number is positive.
Actually if we remove temp. one mediator it should also be fixed. I will reach out to the mediators to unregister one.
