### ISSUE TITLE
Add Whonix 17 Support

### ISSUE THREAD

**Issue by nyxnor** [bisq-network/bisq2#1894]
Hello and thank you for developing Bisq V2.

- Bisq v1.9.14 bootstraps fine.
- Bisq v2.0.1 doesn't bootstrap.

I had to create the dummy tor binary:
```sh
mkdir -p /home/user/.local/share/Bisq2/tor
## Sudo necessary to avoid package overwriting the binary
sudo touch /home/user/.local/share/Bisq2/tor/tor
chmod +x /home/user/.local/share/Bisq2/tor/tor
```

Torrc of Bisqv2 (unmodified by me):
```cfg
HashedControlPassword 16:[REDACTED]
ControlPort 127.0.0.1:34477
Log notice file /home/user/.local/share/Bisq2/tor/debug.log
DataDirectory /home/user/.local/share/Bisq2/tor
SocksPort 44081
DisableNetwork 1
```

Using the command:
```sh
/opt/bisq2/bin/Bisq\ 2 --torControlPort=9051 --torControlPassword=notrequired --socks5ProxyBtcAddress=127.0.0.1:9050 --useTorForBtc=true
```

```
Mar-22 14:58:25.704 [main] INFO  b.d.DesktopAppLauncher: No jar file found. Run default Bisq application with version 2.0.1 
Mar-22 14:58:25.918 [main] INFO  b.a.ApplicationService: 

                    ........                  ......                                                                         
                ..............                ......                                                                         
              .................               ......                                                                         
            ......   ..........   ..          ......                                                                         
           ......      ......   ......        ...............        .....     .........         ..........                  
          .......              ........       ..................     .....   .............     ...............               
          ......               ........       ..........  .......    .....  ......   ...     ........   .......              
         ......                   .....       .......        .....   .....  .....            .....        ......             
         ......    ...        ...             ......         ......  .....   ...........    ......         ......            
         ......   .....      ....             ......         ......  .....    ............  .....          ......            
          ......                               .....         ......  .....         ........ ......         ......            
           ......       ....        ...        ......       ......   .....    ..     ......  ......      ........            
            ........     ..      .......        .................    .....  ..............    ...................            
             ..........       .........           .............      .....   ............       .................            
               ......................                 .....                      ....               ....   ......            
                  ................                                                                         ......            
                        ....                                                                               ......            
                                                                                                           ......            


 
Mar-22 14:58:25.919 [main] INFO  b.a.ApplicationService: Data directory: /home/user/.local/share/Bisq2 
Mar-22 14:58:25.921 [main] INFO  b.a.ApplicationService: Version: 2.0.1 
Mar-22 14:58:25.994 [Scheduler-197-0] INFO  b.c.u.MemoryReport: 
************************************************************************************************************************
Total memory: 96 MB; Used memory: 13.173 MB; Free memory: 82.827 MB; Max memory: 1.447 GB; No. of threads: 2
************************************************************************************************************************ 
Mar-22 14:58:27.423 [Thread-0] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.NullPointerException: Cannot invoke "bisq.desktop_app.DesktopApplicationService.getShutDownErrorMessage()" because "this.applicationService" is null
	at bisq.desktop_app.DesktopExecutable.exitJvm(DesktopExecutable.java:122)
	at bisq.application.Executable.shutdown(Executable.java:49)
	at bisq.application.Executable.lambda$new$0(Executable.java:23)
	at java.base/java.lang.Thread.run(Thread.java:840)

Mar-22 14:58:44.456 [main] INFO  b.d.DesktopAppLauncher: No jar file found. Run default Bisq application with version 2.0.1 
Mar-22 14:58:44.679 [main] INFO  b.a.ApplicationService: 

                    ........                  ......                                                                         
                ..............                ......                                                                         
              .................               ......                                                                         
            ......   ..........   ..          ......                                                                         
           ......      ......   ......        ...............        .....     .........         ..........                  
          .......              ........       ..................     .....   .............     ...............               
          ......               ........       ..........  .......    .....  ......   ...     ........   .......              
         ......                   .....       .......        .....   .....  .....            .....        ......             
         ......    ...        ...             ......         ......  .....   ...........    ......         ......            
         ......   .....      ....             ......         ......  .....    ............  .....          ......            
          ......                               .....         ......  .....         ........ ......         ......            
           ......       ....        ...        ......       ......   .....    ..     ......  ......      ........            
            ........     ..      .......        .................    .....  ..............    ...................            
             ..........       .........           .............      .....   ............       .................            
               ......................                 .....                      ....               ....   ......            
                  ................                                                                         ......            
                        ....                                                                               ......            
                                                                                                           ......            


 
Mar-22 14:58:44.680 [main] INFO  b.a.ApplicationService: Data directory: /home/user/.local/share/Bisq2 
Mar-22 14:58:44.682 [main] INFO  b.a.ApplicationService: Version: 2.0.1 
Mar-22 14:58:44.765 [Scheduler-700-0] INFO  b.c.u.MemoryReport: 
************************************************************************************************************************
Total memory: 96 MB; Used memory: 12.845 MB; Free memory: 83.155 MB; Max memory: 1.447 GB; No. of threads: 2
************************************************************************************************************************ 
Mar-22 14:58:46.092 [main] INFO  b.p.PersistenceService: Read persisted data from:
/home/user/.local/share/Bisq2/db/cache/banned_user_store.protobuf
/home/user/.local/share/Bisq2/db/cache/bisq_easy_offerbook_channel_store.protobuf
/home/user/.local/share/Bisq2/db/cache/network_service_store.protobuf
/home/user/.local/share/Bisq2/db/cache/public_discussion_chat_channel_store.protobuf
/home/user/.local/share/Bisq2/db/cache/public_events_chat_channel_store.protobuf
/home/user/.local/share/Bisq2/db/cache/public_support_chat_channel_store.protobuf
/home/user/.local/share/Bisq2/db/private/account_store.protobuf
/home/user/.local/share/Bisq2/db/private/bisq_easy_open_trade_channel_store.protobuf
/home/user/.local/share/Bisq2/db/private/bisq_easy_trade_store.protobuf
/home/user/.local/share/Bisq2/db/private/identity_store.protobuf
/home/user/.local/share/Bisq2/db/private/key_bundle_store.protobuf
/home/user/.local/share/Bisq2/db/private/mediator_store.protobuf
/home/user/.local/share/Bisq2/db/private/moderator_store.protobuf
/home/user/.local/share/Bisq2/db/private/private_bisq_easy_private_chat_chat_channel_store.protobuf
/home/user/.local/share/Bisq2/db/private/private_discussion_chat_channel_store.protobuf
/home/user/.local/share/Bisq2/db/private/private_events_chat_channel_store.protobuf
/home/user/.local/share/Bisq2/db/private/private_support_chat_channel_store.protobuf
/home/user/.local/share/Bisq2/db/private/resend_message_store.protobuf
/home/user/.local/share/Bisq2/db/private/user_identity_store.protobuf
/home/user/.local/share/Bisq2/db/settings/account_age_store.protobuf
/home/user/.local/share/Bisq2/db/settings/bisq_easy_offerbook_channel_selection_store.protobuf
/home/user/.local/share/Bisq2/db/settings/bisq_easy_open_trades_channel_selection_store.protobuf
/home/user/.local/share/Bisq2/db/settings/bisq_easy_private_chat_channel_selection_store.protobuf
/home/user/.local/share/Bisq2/db/settings/chat_notifications_store.protobuf
/home/user/.local/share/Bisq2/db/settings/discussion_channel_selection_store.protobuf
/home/user/.local/share/Bisq2/db/settings/events_channel_selection_store.protobuf
/home/user/.local/share/Bisq2/db/settings/market_price_store.protobuf
/home/user/.local/share/Bisq2/db/settings/message_delivery_status_store.protobuf
/home/user/.local/share/Bisq2/db/settings/profile_age_store.protobuf
/home/user/.local/share/Bisq2/db/settings/settings_store.protobuf
/home/user/.local/share/Bisq2/db/settings/signed_witness_store.protobuf
/home/user/.local/share/Bisq2/db/settings/support_channel_selection_store.protobuf
/home/user/.local/share/Bisq2/db/settings/tor_peer_group_store.protobuf
/home/user/.local/share/Bisq2/db/settings/user_profile_store.protobuf 
Mar-22 14:58:48.395 [JavaFX Application Thread] INFO  b.d.DesktopExecutable: Java FX Application launched 
Mar-22 14:58:48.947 [PreventStandbyMode-0] INFO  b.d.c.s.Inhibitor: Started -- disabled power management via /usr/bin/systemd-inhibit --who Bisq --what sleep --why Avoid Standby --mode block tail -f /dev/null 
Mar-22 14:58:49.487 [JavaFX Application Thread] INFO  b.s.SecurityService: initialize 
Mar-22 14:58:49.537 [JavaFX Application Thread] INFO  b.d.DesktopApplicationService: New state INITIALIZE_NETWORK 
Mar-22 14:58:49.537 [JavaFX Application Thread] INFO  b.n.NetworkService: initialize 
Mar-22 14:58:49.645 [NetworkService.network-IO-pool-0] INFO  b.n.p.ServiceNode: New state INITIALIZING 
Mar-22 14:58:49.656 [NetworkService.network-IO-pool-0] INFO  b.n.p.n.t.TorTransportService: Initialize Tor 
Mar-22 14:58:50.245 [JavaFX Application Thread] INFO  b.d.DesktopView: Attaching view to stage took 1380 ms 
Mar-22 14:59:44.767 [Scheduler-700-0] INFO  b.c.u.MemoryReport: 
************************************************************************************************************************
Total memory: 102 MB; Used memory: 64.783 MB; Free memory: 37.217 MB; Max memory: 1.447 GB; No. of threads: 15
************************************************************************************************************************ 
Mar-22 14:59:49.764 [NetworkService.network-IO-pool-0] ERROR b.t.p.NativeTorProcess: Couldn't wait for log file creation. java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at bisq.common.scanner.FileScanner.waitUntilLogContainsLines(FileScanner.java:44)
	at bisq.tor.process.NativeTorProcess.waitUntilControlPortReady(NativeTorProcess.java:85)
	at bisq.tor.TorService.initialize(TorService.java:93)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:133)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

Mar-22 14:59:49.768 [NetworkService.network-IO-pool-0] ERROR b.d.DesktopApplicationService: Error at networkFuture.initialize java.util.concurrent.CompletionException: java.lang.IllegalStateException: Couldn't wait for log file creation.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Couldn't wait for log file creation.
	at bisq.tor.process.NativeTorProcess.waitUntilControlPortReady(NativeTorProcess.java:90)
	at bisq.tor.TorService.initialize(TorService.java:93)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:133)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 common frames omitted

Mar-22 14:59:49.771 [NetworkService.network-IO-pool-0] ERROR b.d.DesktopApplicationService: Initializing applicationService failed java.util.concurrent.CompletionException: java.lang.IllegalStateException: Couldn't wait for log file creation.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Couldn't wait for log file creation.
	at bisq.tor.process.NativeTorProcess.waitUntilControlPortReady(NativeTorProcess.java:90)
	at bisq.tor.TorService.initialize(TorService.java:93)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:133)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 common frames omitted

Mar-22 14:59:49.774 [NetworkService.network-IO-pool-0] INFO  b.d.DesktopApplicationService: New state FAILED 
Mar-22 15:00:14.139 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = kde-open args = %s file = /home/user/.local/share/Bisq2/bisq.log 
Mar-22 15:00:14.142 [JavaFX Application Thread] WARN  b.c.u.OsUtils: Error running command. java.io.IOException: Cannot run program "kde-open": error=2, No such file or directory 
Mar-22 15:00:14.142 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = gnome-open args = %s file = /home/user/.local/share/Bisq2/bisq.log 
Mar-22 15:00:14.145 [JavaFX Application Thread] WARN  b.c.u.OsUtils: Error running command. java.io.IOException: Cannot run program "gnome-open": error=2, No such file or directory 
Mar-22 15:00:14.145 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = xdg-open args = %s file = /home/user/.local/share/Bisq2/bisq.log 
Mar-22 15:00:14.147 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Process is running. 
```

So, is there a command line option to skip creating the tor log file?

I don't see to find the command line help option
```sh
/opt/bisq2/bin/Bisq\ 2 -h --help -help help
## Starts Bisq
````

Tor bootstrap always stops at 24% and I never see it reach onion-grater on the Whonix-Gateway.

**Comment by adrelanos** [comment]
**Issue 1)**

Above issue will most likely be resolved in next Bisq 2 release thanks to https://github.com/bisq-network/bisq2/pull/1914.

----

**Issue 2)**

But now I am running into a different issue.

Using Bisq 2 from git.
(`dbc8e400fdb28324a1bf7d928f3be7e4cf9f4a63`)

> 19:28:24.982 ERROR [NetworkService.network-IO-pool-0] b.d.DesktopApplicationService: Initializing applicationService failed java.util.concurrent.CompletionException: bisq.common.archive.ZipFileExtractionFailedException: Couldn't write to stream to: /home/user/.local/share/Bisq2/tor/tor

In Whonix Bisq documentation chapter [Tor over Tor Prevention](https://www.whonix.org/wiki/Bisq#Tor_over_Tor_Prevention) we currently suggest:

    mkdir -p /home/user/.local/share/Bisq2/tor/
    sudo ln -s /usr/bin/tor /home/user/.local/share/Bisq2/tor/tor

The `/usr/bin/tor` in Whonix-Workstation we call [Tor binary replacement](https://www.whonix.org/wiki/Dev/anon-ws-disable-stacked-tor#Tor_binary_replacement). It is supposed to emulate what Bisq needs.

Something similar worked for Bisq 1. But even that is no longer possible with Bisq 2.

The most useful change would be honor environment variable `TOR_SKIP_LAUNCH=1`. If that is set, then Bisq 2 should:

* abstain from creating file `/home/user/.local/share/Bisq2/tor/tor`
* do not wait for any Tor log files
* do not wait for Tor control port
* simply assume an already functional system Tor and use it. Using default system Tor ports `SocksPort 9051` `ControlPort 9051`. That would be a good start better Tor integration.

----

**Issue 3)**

I was able to workaround Issue 2) by initially letting Bisq create file, then stopping Bisq, then deleting file `/home/user/.local/share/Bisq2/tor/tor`, `sudo ln -s /usr/bin/tor /home/user/.local/share/Bisq2/tor/tor`.

But Bisq is still waiting for some Tor log file which it cannot find.

```
Mar-24 19:39:04.082 [NetworkService.network-IO-pool-0] ERROR b.t.p.NativeTorProcess: Couldn't wait for log file creation. java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.nio.file.WatchKey.pollEvents()" because "watchKey" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at bisq.common.scanner.FileScanner.waitUntilLogContainsLines(FileScanner.java:44)
	at bisq.tor.process.NativeTorProcess.waitUntilControlPortReady(NativeTorProcess.java:85)
	at bisq.tor.TorService.initialize(TorService.java:93)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:133)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.WatchKey.pollEvents()" because "watchKey" is null
	at bisq.common.FileCreationWatcher.waitForNewFile(FileCreationWatcher.java:55)
	at bisq.common.FileCreationWatcher.lambda$waitForFile$1(FileCreationWatcher.java:45)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 common frames omitted

Mar-24 19:39:04.083 [NetworkService.network-IO-pool-0] ERROR b.d.DesktopApplicationService: Error at networkFuture.initialize java.util.concurrent.CompletionException: java.lang.IllegalStateException: Couldn't wait for log file creation.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Couldn't wait for log file creation.
	at bisq.tor.process.NativeTorProcess.waitUntilControlPortReady(NativeTorProcess.java:90)
	at bisq.tor.TorService.initialize(TorService.java:93)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:133)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 common frames omitted

Mar-24 19:39:04.083 [NetworkService.network-IO-pool-0] ERROR b.d.DesktopApplicationService: Initializing applicationService failed java.util.concurrent.CompletionException: java.lang.IllegalStateException: Couldn't wait for log file creation.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.IllegalStateException: Couldn't wait for log file creation.
	at bisq.tor.process.NativeTorProcess.waitUntilControlPortReady(NativeTorProcess.java:90)
	at bisq.tor.TorService.initialize(TorService.java:93)
	at bisq.network.p2p.node.transport.TorTransportService.initialize(TorTransportService.java:63)
	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:229)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:133)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 common frames omitted

Mar-24 19:39:04.083 [NetworkService.network-IO-pool-0] INFO  b.d.DesktopApplicationService: New state FAILED 
Mar-24 19:39:18.462 [JavaFX Application Thread] WARN  b.d.c.o.Popup$Manager: We got a isHidden called with a popup to existing in our displayedPopups. 
Mar-24 19:39:21.022 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = kde-open args = %s file = /home/user/.local/share/Bisq2/bisq.log 
Mar-24 19:39:21.024 [JavaFX Application Thread] WARN  b.c.u.OsUtils: Error running command. java.io.IOException: Cannot run program "kde-open": error=2, No such file or directory 
Mar-24 19:39:21.024 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = gnome-open args = %s file = /home/user/.local/share/Bisq2/bisq.log 
Mar-24 19:39:21.026 [JavaFX Application Thread] WARN  b.c.u.OsUtils: Error running command. java.io.IOException: Cannot run program "gnome-open": error=2, No such file or directory 
Mar-24 19:39:21.026 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Trying to exec: cmd = xdg-open args = %s file = /home/user/.local/share/Bisq2/bisq.log 
Mar-24 19:39:21.042 [JavaFX Application Thread] INFO  b.c.u.OsUtils: Process is running. 
Mar-24 19:40:02.437 [Scheduler-227-0] INFO  b.c.u.MemoryReport: 
************************************************************************************************************************
Total memory: 84 MB; Used memory: 78.396 MB; Free memory: 5.604 MB; Max memory: 976 MB; No. of threads: 14
************************************************************************************************************************ 
Mar-24 19:40:49.127 [JavaFX Application Thread] INFO  b.d.DesktopExecutable: Exiting JavaFX Platform 
Mar-24 19:40:49.128 [JavaFX Application Thread] INFO  b.a.Executable: Exiting JVM 
Mar-24 19:40:49.131 [Thread-0] INFO  b.d.DesktopApplicationService: shutdown
```

Maybe deprecation of parsing Tor's log file in https://github.com/bisq-network/bisq2/pull/1914 was incomplete?

**Comment by HenrikJannsen** [comment]
This is fixed for next release.

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?

**Comment by nyxnor** [comment]
> Can you try it out?

Yes, I can. Due to @alvasw PR on https://github.com/bisq-network/bisq2/pull/2286 and PR on https://github.com/Whonix/onion-grater/pull/11, I will be able to test only in 2.0.5.

**Comment by HenrikJannsen** [comment]
Here is a PR implementing support for connecting to an external Tor process: https://github.com/bisq-network/bisq2/pull/3046
