### ISSUE TITLE
Unable to send message in trade chat

### ISSUE THREAD

**Issue by strayorigin** [bisq-network/bisq2#1899]
The peer had sent me a message in the trade chat and when replying back and hitting send, I receive the following error message and the message is not sent.  

```
java.lang.NullPointerException: user identity must not be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
	at bisq.desktop.main.content.components.chatMessages.ChatMessagesComponent$Controller.doSendMessage(ChatMessagesComponent.java:310)
	at bisq.desktop.main.content.components.chatMessages.ChatMessagesComponent$Controller.onSendMessage(ChatMessagesComponent.java:295)
	at bisq.desktop.main.content.components.chatMessages.ChatMessagesComponent$View.lambda$onViewAttached$3(ChatMessagesComponent.java:460)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.disp...
```

**Comment by HenrikJannsen** [comment]
It was caused in `ChatMessagesComponent`:
`UserIdentity userIdentity = checkNotNull(userIdentityService.getSelectedUserIdentity(), "user identity must not be null");`

Seems to be bug that the  `selectedUserIdentity` is not set correctly.

**Comment by suddenwhipvapor** [comment]
Reporting similar issue forwarded to me by a user:

![image](https://github.com/bisq-network/bisq2/assets/124399749/d87c6084-2503-408e-a770-0f293c306442)

![image](https://github.com/bisq-network/bisq2/assets/124399749/13a88f0c-d930-479c-80e6-ad4800582e85)

```
[JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.NullPointerException: user identity must not be null
	at [com.google](http://com.google/).common.base.Preconditions.checkNotNull([Preconditions.java:907](http://preconditions.java:907/))
	at bisq.desktop.main.content.components.chatMessages.ChatMessagesComponent$Controller.doSendMessage([ChatMessagesComponent.java:316](http://chatmessagescomponent.java:316/))
	at bisq.desktop.main.content.components.chatMessages.ChatMessagesComponent$Controller.onSendMessage([ChatMessagesComponent.java:301](http://chatmessagescomponent.java:301/))
	at bisq.desktop.main.content.components.chatMessages.ChatMessagesComponent$View.lambda$onViewAttached$2([ChatMessagesComponent.java:462](http://chatmessagescomponent.java:462/))
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent([CompositeEventHandler.java:86](http://compositeeventhandler.java:86/))
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent([EventHandlerManager.java:234](http://eventhandlermanager.java:234/))
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent([EventHandlerManager.java:191](http://eventhandlermanager.java:191/))
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent([CompositeEventDispatcher.java:59](http://compositeeventdispatcher.java:59/))
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent([BasicEventDispatcher.java:58](http://basiceventdispatcher.java:58/))
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent([EventDispatchChainImpl.java:114](http://eventdispatchchainimpl.java:114/))
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent([BasicEventDispatcher.java:56](http://basiceventdispatcher.java:56/))
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent([EventDispatchChainImpl.java:114](http://eventdispatchchainimpl.java:114/))
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent([BasicEventDispatcher.java:56](http://basiceventdispatcher.java:56/))
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent([EventDispatchChainImpl.java:114](http://eventdispatchchainimpl.java:114/))
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl([EventUtil.java:74](http://eventutil.java:74/))
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent([EventUtil.java:54](http://eventutil.java:54/))
	at javafx.base/javafx.event.Event.fireEvent([Event.java:198](http://event.java:198/))
	at [javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4105)](http://javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4105))
	at [javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2156)](http://javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2156))
	at [javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2630)](http://javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2630))
	at [javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218)](http://javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:218))
	at [javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150)](http://javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:150))
	at java.base/[java.security](http://java.security/).AccessController.doPrivileged([AccessController.java:399](http://accesscontroller.java:399/))
	at [javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250)](http://javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:250))
	at [javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:423)](http://javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:423))
	at [javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249)](http://javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:249))
	at [javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:542)](http://javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:542))
	at [javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:966)](http://javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:966))
	at [javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native](http://javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native) Method)
	at [javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)](http://javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290))
	at java.base/[java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:840](http://thread.java:840/))
```

**Comment by HenrikJannsen** [comment]
@suddenwhipvapor Do you got the full logs from one user who had that issue? If not can you request the log files?

**Comment by HenrikJannsen** [comment]
Can you also ask then if they have deleted a user profile before? In the code path that is the only way to set the selected user to null but it should be set then to the next available profile and there must be at least 1 left. If thats not the case it could have happened by corrupted persistence files.

**Comment by suddenwhipvapor** [comment]
> @suddenwhipvapor Do you got the full logs from one user who had that issue? If not can you request the log files?

On it, for both the logs  and the old profile status

**Comment by suddenwhipvapor** [comment]
sent you the requested data 👌🏻
