### ISSUE TITLE
Unable to take sell trade as buyer for some sell offers

### ISSUE THREAD

**Issue by polishboi** [bisq-network/bisq2#1926]
Version: v2.0.1
Platform: MacOS
Happens for any sell offers that have ranges
Seller: L8Knighter [Seemingly-Eruptive-Anecdote-880] EUR USD
Seller: Verbist EUR

Firstly the conversion to bitcoin does not appear in this particular trade (all L8Knighter's trades: EUR, USD). Also moving the slider does not change the amount.

<img width="959" alt="image" src="https://github.com/bisq-network/bisq2/assets/48173986/0fa704a1-ddf0-48e8-a801-6d5c61d18866">
I pick the method then get this
<img width="920" alt="image" src="https://github.com/bisq-network/bisq2/assets/48173986/444d95f6-7736-4715-9bba-8d3d1d7cb467">

```
mar-24 21:59:24.984 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
mar-24 21:59:24.984 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.NullPointerException: Cannot invoke "bisq.common.monetary.Monetary.getPrecision()" because "amount" is null
	at bisq.presentation.formatters.AmountFormatter.getDecimalFormat(AmountFormatter.java:93)
	at bisq.presentation.formatters.AmountFormatter.formatAmount(AmountFormatter.java:61)
	at bisq.presentation.formatters.AmountFormatter.formatAmount(AmountFormatter.java:53)
	at bisq.desktop.main.content.bisq_easy.take_offer.review.TakeOfferReviewController.onActivate(TakeOfferReviewController.java:267)
	at bisq.desktop.common.view.Controller.onActivateInternal(Controller.java:31)
	at bisq.desktop.common.view.View.onViewAttachedPrivate(View.java:92)
	at bisq.desktop.common.view.View.handleSceneChange(View.java:54)
	at bisq.desktop.common.view.View.lambda$new$0(View.java:46)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1046)
	at javafx.scene.Node.invalidatedScenes(Node.java:1097)
	at javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.scene.Parent$2.onChanged(Parent.java:372)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:98)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at bisq.desktop.main.content.bisq_easy.take_offer.TakeOfferView.lambda$new$0(TakeOfferView.java:119)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at bisq.desktop.common.view.NavigationModel.setView(NavigationModel.java:55)
	at bisq.desktop.common.view.NavigationController.processNavigationTarget(NavigationController.java:54)
	at bisq.desktop.common.view.Navigation.lambda$navigateTo$1(Navigation.java:66)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.common.view.Navigation.lambda$navigateTo$2(Navigation.java:66)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at bisq.desktop.common.view.Navigation.navigateTo(Navigation.java:64)
	at bisq.desktop.main.content.bisq_easy.take_offer.TakeOfferController.onNext(TakeOfferController.java:230)
	at bisq.desktop.main.content.bisq_easy.take_offer.TakeOfferView.lambda$onViewAttached$4(TakeOfferView.java:200)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8792)
	at javafx.scene.control.Button.fire(Button.java:203)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1878)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
	at com.sun.glass.ui.View.notifyMouse(View.java:943)
	at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

I press "Close" then "X" and get this:

<img width="987" alt="image" src="https://github.com/bisq-network/bisq2/assets/48173986/2b72c984-a402-44d0-be06-9fdeea2a9ca0">

```
////////////////////////////////////////////////////////////////////////////////////////////////////
Network statistics
////////////////////////////////////////////////////////////////////////////////////////////////////
Number of Connections: 8
Number of messages sent in last hour: 41
Number of messages received in last hour: 38
Size of network DB: 2.538577 MB
Data sent in last hour: 391.722 KB
Data received in last hour: 442.261 KB
Time for message sending in last hour: 0.117 sec.
Time for message deserializing in last hour: 0.608 sec.
////////////////////////////////////////////////////////////////////////////////////////////////////
 
mar-24 21:53:58.706 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.NullPointerException: Cannot invoke "org.fxmisc.easybind.Subscription.unsubscribe()" because "this.showTakeOfferSuccessPin" is null
	at bisq.desktop.main.content.bisq_easy.take_offer.review.TakeOfferReviewView.onViewDetached(TakeOfferReviewView.java:177)
	at bisq.desktop.common.view.View.onViewDetachedInternal(View.java:102)
	at bisq.desktop.common.view.View.onViewDetachedPrivate(View.java:86)
	at bisq.desktop.common.view.View.handleSceneChange(View.java:68)
	at bisq.desktop.common.view.View.lambda$new$0(View.java:46)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1046)
	at javafx.scene.Node.invalidatedScenes(Node.java:1097)
	at javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.scene.Parent.scenesChanged(Parent.java:772)
	at javafx.scene.Node.invalidatedScenes(Node.java:1068)
	at javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.scene.Parent.scenesChanged(Parent.java:772)
	at javafx.scene.Node.invalidatedScenes(Node.java:1068)
	at javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.scene.Parent$3.onProposedChange(Parent.java:605)
	at com.sun.javafx.collections.VetoableListDecorator.clear(VetoableListDecorator.java:293)
	at bisq.desktop.overlay.OverlayView.lambda$hide$5(OverlayView.java:191)
	at bisq.desktop.overlay.OverlayView.lambda$animateHide$7(OverlayView.java:243)
	at javafx.animation.Animation.runHandler(Animation.java:1102)
	at javafx.animation.Animation.finished(Animation.java:1096)
	at javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:107)
	at javafx.animation.Animation.doTimePulse(Animation.java:1189)
	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:207)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.animation.Animation$1.timePulse(Animation.java:206)
	at com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:571)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

mar-24 21:53:58.723 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
mar-24 21:53:58.725 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.NullPointerException: Cannot invoke "org.fxmisc.easybind.Subscription.unsubscribe()" because "this.showTakeOfferSuccessPin" is null
	at bisq.desktop.main.content.bisq_easy.take_offer.review.TakeOfferReviewView.onViewDetached(TakeOfferReviewView.java:177)
	at bisq.desktop.common.view.View.onViewDetachedInternal(View.java:102)
	at bisq.desktop.common.view.View.onViewDetachedPrivate(View.java:86)
	at bisq.desktop.common.view.View.handleSceneChange(View.java:68)
	at bisq.desktop.common.view.View.lambda$new$0(View.java:46)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1046)
	at javafx.scene.Node.invalidatedScenes(Node.java:1097)
	at javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.scene.Parent.scenesChanged(Parent.java:772)
	at javafx.scene.Node.invalidatedScenes(Node.java:1068)
	at javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.scene.Parent.scenesChanged(Parent.java:772)
	at javafx.scene.Node.invalidatedScenes(Node.java:1068)
	at javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.scene.Parent$3.onProposedChange(Parent.java:605)
	at com.sun.javafx.collections.VetoableListDecorator.clear(VetoableListDecorator.java:293)
	at bisq.desktop.overlay.OverlayView.lambda$hide$5(OverlayView.java:191)
	at bisq.desktop.overlay.OverlayView.lambda$animateHide$7(OverlayView.java:243)
	at javafx.animation.Animation.runHandler(Animation.java:1102)
	at javafx.animation.Animation.finished(Animation.java:1096)
	at javafx.animation.AnimationAccessorImpl.finished(AnimationAccessorImpl.java:49)
	at com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(SingleLoopClipEnvelope.java:107)
	at javafx.animation.Animation.doTimePulse(Animation.java:1189)
	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:207)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.animation.Animation$1.timePulse(Animation.java:206)
	at com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:343)
	at com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:571)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)

mar-24 21:54:17.316 [Scheduler-617-0] INFO  b.c.u.MemoryReport: 
************************************************************************************************************************
Total memory: 562 MB; Used memory: 261,298 MB; Free memory: 300,702 MB; Max memory: 2 GB; No. of threads: 73
************************************************************************************************************************ 
mar-24 21:54:18.131 [Scheduler-18-0] INFO  b.n.p.s.d.s.a.AuthenticatedDataStorageService: We remove 1 expired entries from our map 
mar-24 21:55:07.447 [Connection.read-[xiuh7lzg3hd7zg74omm725cmxlij...] INFO  b.n.p.n.Connection: Close 'OutboundConnection [peerAddress=[xiuh7lzg3hd7zg74omm725cmxlijeyrhghghikmef5u6x73bng4jfkid.onion:30435], keyId=e
```

Possible duplicate https://github.com/bisq-network/bisq2/issues/1728

**Comment by HenrikJannsen** [comment]
I suspect that its solved by other bugfixes in that area. If you are a dev and able to run from source code, could you try the latest main branch to see if it still happens?

**Comment by HenrikJannsen** [comment]
version 2.0.2 is out as pre-release. Can you try out with that if you get that error again?
https://github.com/bisq-network/bisq2/releases/v2.0.2

**Comment by HenrikJannsen** [comment]
This is fixed for next release.
It is caused by the language difference of the maker and yourself. Top mitigate with current version you can either change your language to the estimated of the maker or to take another offer in the same language.
