### ISSUE TITLE
Error Upgrading Bisq 2.0.1 to 2.0.2 from Installer

### ISSUE THREAD

**Issue by 91anon93** [bisq-network/bisq2#1951]
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 400 for URL: https://github.com/bisq-network/bisq2/releases/download/v2.0.2/Bisq 2-2.0.2.deb.asc
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: ...
[bisq.log](https://github.com/bisq-network/bisq2/files/14789438/bisq.log)

**Comment by jalal** [comment]
Can confirm here
Linux Ubuntu 22.04.4

**Comment by 91anon93** [comment]
Pop OS 22.04 LTS

**Comment by HenrikJannsen** [comment]
Its a known issue fixed in 2.0.2 for next release. Please download directly at https://github.com/bisq-network/bisq2/releases/v2.0.2
