### ISSUE TITLE
Unable to execute trade on GBP

### ISSUE THREAD

**Issue by msxakk89** [bisq-network/bisq2#1954]
I tried to buy using BisqEasy but got the following error:

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at bisq.support.mediation.MediationRequestService.selectMediator(MediationRequestService.java:151)
	at bisq.support.mediation.MediationRequestService.selectMediator(MediationRequestService.java:132)
	at bisq.desktop.main.content.bisq_easy.take_offer.review.TakeOfferReviewController.takeOffer(TakeOfferReviewController.java:196)
	at bisq.desktop.main....

**Comment by HenrikJannsen** [comment]
Can you install the latest release from https://github.com/bisq-network/bisq2/releases/v2.0.2?
