### ISSUE TITLE
Error when trying to take offer (NullPointerException because value is empty)

### ISSUE THREAD

**Issue by SebZiHub** [bisq-network/bisq2#1961]
Bisq version: 2.0.2-1 on Ubuntu 22.04.4 LTS
Steps to reproduce:

- Open offer book in the "Bisq Easy" protocol
- Select Market
- Click on "Take offer"
- Put value in the field "Percent above market price", e.g. 8

Note: at this point the fixed price field doesn't get update, as it did in the previous versions:

![image](https://github.com/bisq-network/bisq2/assets/19263542/fde3143b-0533-4435-9b7d-71d01ee91ecd)

- Click Next
- Put "500" in the "How much do you want to trade field"

Note: at this point, the slider below doesn't show any value in BTC, I'm assuming this could already be related to the NullPointerException issue, because also the previous fixed price field wasn't updated:

![image](https://github.com/bisq-network/bisq2/assets/19263542/4d6a7dda-07a6-4621-8dc4-abe207f5f356)

- Click on next and select "SEPA Instant", Click Next again, error appears:

![image](https://github.com/bisq-network/bisq2/assets/19263542/c0b2f17e-b22b-4e7a-b3f7-5a5cc50f58a0)

```
Mar-31 10:29:22.608 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.NullPointerException: Cannot invoke "bisq.common.monetary.Monetary.getPrecision()" because "amount" is null
	at bisq.presentation.formatters.AmountFormatter.getDecimalFormat(AmountFormatter.java:93)
	at bisq.presentation.formatters.AmountFormatter.formatAmount(AmountFormatter.java:61)
	at bisq.presentation.formatters.AmountFormatter.formatAmount(AmountFormatter.java:53)
	at bisq.desktop.main.content.bisq_easy.take_offer.review.TakeOfferReviewController.onActivate(TakeOfferReviewController.java:268)
	at bisq.desktop.common.view.Controller.onActivateInternal(Controller.java:31)
	at bisq.desktop.common.view.View.onViewAttachedPrivate(View.java:100)
	at bisq.desktop.common.view.View.handleSceneChange(View.java:55)
	at bisq.desktop.common.view.View.lambda$new$0(View.java:47)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1046)
	at javafx.scene.Node.invalidatedScenes(Node.java:1097)
	at javafx.scene.Node.setScenes(Node.java:1135)
	at javafx.scene.Parent$2.onChanged(Parent.java:372)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:98)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at bisq.desktop.main.content.bisq_easy.take_offer.TakeOfferView.lambda$new$0(TakeOfferView.java:119)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at bisq.desktop.common.view.NavigationModel.setView(NavigationModel.java:55)
	at bisq.desktop.common.view.NavigationController.processNavigationTarget(NavigationController.java:54)
	at bisq.desktop.common.view.Navigation.lambda$navigateTo$1(Navigation.java:66)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.common.view.Navigation.lambda$navigateTo$2(Navigation.java:66)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at bisq.desktop.common.view.Navigation.navigateTo(Navigation.java:64)
	at bisq.desktop.main.content.bisq_easy.take_offer.TakeOfferController.onNext(TakeOfferController.java:230)
	at bisq.desktop.main.content.bisq_easy.take_offer.TakeOfferView.lambda$onViewAttached$4(TakeOfferView.java:200)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8792)
	at javafx.scene.control.Button.fire(Button.java:203)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1878)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:423)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

After closing the error, all fields are empty:

![image](https://github.com/bisq-network/bisq2/assets/19263542/ab2c5cf6-6065-4402-804d-749fb7ab3fc0)

**Comment by HenrikJannsen** [comment]
Thanks for reporting. It is already fixed in https://github.com/bisq-network/bisq2/pull/1960
For now you can either run from source code to avoid that but or take another offer. Or tell the maker that they should re-create the offer while using English instead of another language (I saw it was caused with a spanish offer, but could happen with other languages as well).
