### ISSUE TITLE
Validation issue when selling BTC

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/bisq2#1974]
I was just testing the current main state trying to create a sell offer ending in an endless popup validation regarding the price.

1. Go to Bisq Easy
2. Create an offer
3. Sell without reputation
4. Currency EUR

When entering the price step a validation of the price takes place that prevents the user to continue creating a sell offer.

<img width="1512" alt="Bildschirmfoto 2024-04-02 um 12 45 43" src="https://github.com/bisq-network/bisq2/assets/170962/b7b6cdc4-5eaa-485a-8f96-b1337ff4aa2c">

**Comment by axpoems** [comment]
@ripcurlx I can't repro (tried using German as well). Are you able to repro this consistently? Perhaps you could upload logs?

**Comment by ripcurlx** [comment]
I can repeat it everytime. Unfortunately I don't see anything useful in the logs
```
11:51:13.232 INFO  [NetworkLoadExchangeService.updateNetworkLoadScheduler] b.n.p.n.n.NetworkLoadService: 

////////////////////////////////////////////////////////////////////////////////////////////////////
Network statistics
////////////////////////////////////////////////////////////////////////////////////////////////////
Number of Connections: 2
Number of messages sent in last hour: 16
Number of messages received in last hour: 16
Size of network DB: 0.004371 MB
Data sent in last hour: 5.306 KB
Data received in last hour: 4.033 KB
Time for message sending in last hour: 0.052 sec.
Time for message deserializing in last hour: 0.03 sec.
////////////////////////////////////////////////////////////////////////////////////////////////////
 
11:51:13.233 DEBUG [NetworkLoadExchangeService.updateNetworkLoadScheduler] b.n.p.n.n.NetworkLoadService: 
numConnectionsImpact=0.006666666666666667
sentBytesImpact=2.6530000000000002E-5
spentSendTimeImpact=8.666666666666667E-5
numMessagesSentImpact=8.0E-4
receivedBytesImpact=2.0165E-5
deserializeTimeImpact=5.0E-5
numMessagesReceivedImpact=0.0016
networkDatabaseSizeImpact=1.3113E-5
sum=0.009263141333333334 
11:51:13.385 INFO  [PeerExchangeService.scheduler-Node wi...] b.n.p.s.p.e.PeerExchangeStrategy: We reset the usedAddresses and try again to connect to peers we tried in the past. 
11:51:13.385 INFO  [PeerExchangeService.scheduler-Node wi...] b.n.p.s.p.e.PeerExchangeService: startInitialPeerExchange [[8000], [8001], [60181]] 
11:51:13.386 INFO  [PeerExchangeService.scheduler-Node wi...] b.n.p.s.p.e.PeerExchangeService: Node with address [54223] starts peer exchange with: [[8000], [8001], [60181]] 
11:51:13.448 DEBUG [NetworkService.network-IO-pool-9] b.n.p.n.Node: Create outbound connection to [8001] 
11:51:13.448 DEBUG [NetworkService.network-IO-pool-9] b.n.p.n.t.ClearNetTransportService: Create new Socket to [8001] 
11:51:13.448 DEBUG [NetworkService.network-IO-pool-10] b.n.p.s.p.e.PeerExchangeRequestHandler: Node with address [54223] send PeerExchangeRequest to [60181] with 0 peers 
11:51:13.448 DEBUG [NetworkService.network-IO-pool-8] b.n.p.s.p.e.PeerExchangeRequestHandler: Node with address [54223] send PeerExchangeRequest to [8000] with 1 peers 
11:51:13.449 DEBUG [NetworkService.network-IO-pool-9] b.n.p.n.Node: Node with address [54223] got called handleException. exception=Connection refused 
11:51:13.450 DEBUG [NetworkService.network-IO-pool-9] b.n.p.n.Node: Exception:  java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:639)
	at java.base/java.net.Socket.connect(Socket.java:588)
	at java.base/java.net.Socket.<init>(Socket.java:512)
	at java.base/java.net.Socket.<init>(Socket.java:292)
	at bisq.network.p2p.node.transport.ClearNetTransportService.getSocket(ClearNetTransportService.java:113)
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:382)
	at bisq.network.p2p.node.Node.lambda$createOutboundConnection$8(Node.java:364)
	at java.base/java.util.Optional.map(Optional.java:260)
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:364)
	at bisq.network.p2p.node.Node.getConnection(Node.java:353)
	at bisq.network.p2p.services.peergroup.exchange.PeerExchangeService.doPeerExchange(PeerExchangeService.java:214)
	at bisq.network.p2p.services.peergroup.exchange.PeerExchangeService.lambda$doPeerExchangeAsync$5(PeerExchangeService.java:208)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:639)
	at java.base/java.net.Socket.connect(Socket.java:588)
	at java.base/java.net.Socket.<init>(Socket.java:512)
	at java.base/java.net.Socket.<init>(Socket.java:292)
	at bisq.network.p2p.node.transport.ClearNetTransportService.getSocket(ClearNetTransportService.java:113)
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:382)
	at bisq.network.p2p.node.Node.lambda$createOutboundConnection$8(Node.java:364)
	at java.base/java.util.Optional.map(Optional.java:260)
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:364)
	at bisq.network.p2p.node.Node.getConnection(Node.java:353)
	at bisq.network.p2p.services.peergroup.exchange.PeerExchangeService.doPeerExchange(PeerExchangeService.java:214)
	at bisq.network.p2p.services.peergroup.exchange.PeerExchangeService.lambda$doPeerExchangeAsync$5(PeerExchangeService.java:208)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
11:51:13.450 DEBUG [NetworkService.network-IO-pool-10] b.n.p.n.a.t.h.HashCashTokenService: Create HashCashToken for PeerExchangeRequest took 1 ms
costFactor=0.1
getPayload(message)=2206088affb7be06
networkLoad=NetworkLoad(load=0.008980088, difficultyAdjustmentFactor=1.0)
hashCashToken=HashCashToken(proofOfWork=ProofOfWork{
duration=1
difficulty=2^7.0 = 128.0
counter=72
challenge=d85682935f22f3a8143e0f421a58d277823a7b399d4a84e0bf3a38c0426a00cf
solution=0000000000000048
payload=2206088affb7be06}, messageCounter=8) 
11:51:13.450 DEBUG [NetworkService.network-IO-pool-9] b.n.p.s.p.e.PeerExchangeService: Node with address [54223] failed to do a peer exchange with [8001]. bisq.network.p2p.node.ConnectionException: java.net.ConnectException: Connection refused
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:385)
	at bisq.network.p2p.node.Node.lambda$createOutboundConnection$8(Node.java:364)
	at java.base/java.util.Optional.map(Optional.java:260)
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:364)
	at bisq.network.p2p.node.Node.getConnection(Node.java:353)
	at bisq.network.p2p.services.peergroup.exchange.PeerExchangeService.doPeerExchange(PeerExchangeService.java:214)
	at bisq.network.p2p.services.peergroup.exchange.PeerExchangeService.lambda$doPeerExchangeAsync$5(PeerExchangeService.java:208)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:639)
	at java.base/java.net.Socket.connect(Socket.java:588)
	at java.base/java.net.Socket.<init>(Socket.java:512)
	at java.base/java.net.Socket.<init>(Socket.java:292)
	at bisq.network.p2p.node.transport.ClearNetTransportService.getSocket(ClearNetTransportService.java:113)
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:382)
	... 10 common frames omitted

bisq.network.p2p.node.ConnectionException: java.net.ConnectException: Connection refused
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:385)
	at bisq.network.p2p.node.Node.lambda$createOutboundConnection$8(Node.java:364)
	at java.base/java.util.Optional.map(Optional.java:260)
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:364)
	at bisq.network.p2p.node.Node.getConnection(Node.java:353)
	at bisq.network.p2p.services.peergroup.exchange.PeerExchangeService.doPeerExchange(PeerExchangeService.java:214)
	at bisq.network.p2p.services.peergroup.exchange.PeerExchangeService.lambda$doPeerExchangeAsync$5(PeerExchangeService.java:208)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:639)
	at java.base/java.net.Socket.connect(Socket.java:588)
	at java.base/java.net.Socket.<init>(Socket.java:512)
	at java.base/java.net.Socket.<init>(Socket.java:292)
	at bisq.network.p2p.node.transport.ClearNetTransportService.getSocket(ClearNetTransportService.java:113)
	at bisq.network.p2p.node.Node.createOutboundConnection(Node.java:382)
	... 10 common frames omitted
11:51:13.451 DEBUG [NetworkService.network-IO-pool-10] b.n.p.n.Connection: Sent PeerExchangeRequest(nonce=870776773, peers=[]) from 'OutboundConnection [peerAddress=[60181], keyId=8ac7fb69-8036-4a18-903c-b68131711d8f]' 
11:51:13.451 DEBUG [NetworkService.network-IO-pool-8] b.n.p.n.a.t.h.HashCashTokenService: Create HashCashToken for PeerExchangeRequest took 2 ms
costFactor=0.1
getPayload(message)=224308bbf78ca107123b0a1c0a0f0a093132372e302e302e3110aaac071205434c4541521a020103121209229d33022764823f11000000000000f03f180120d0a0f5b5d463
networkLoad=NetworkLoad(load=0.008163154666666667, difficultyAdjustmentFactor=1.0)
hashCashToken=HashCashToken(proofOfWork=ProofOfWork{
duration=2
difficulty=2^7.0 = 128.0
counter=333
challenge=f2ce55fd7eef7bb53c02d71e0d46e3283a9806a0b75395321b177fa62bc014d2
solution=000000000000014d
payload=224308bbf78ca107123b0a1c0a0f0a093132372e302e302e3110aaac071205434c4541521a020103121209229d33022764823f11000000000000f03f180120d0a0f5b5d463}, messageCounter=8) 
11:51:13.452 DEBUG [NetworkService.network-IO-pool-8] b.n.p.n.Connection: Sent PeerExchangeRequest(nonce=-974233054, peers=[Peer(address=[60181], capability=Capability(address=[60181], supportedTransportTypes=[CLEAR], features=[INVENTORY_HASH_SET, AUTHORIZATION_HASH_CASH]), networkLoad=NetworkLoad(load=0.008980088, difficultyAdjustmentFactor=1.0), isOutboundConnection=true,... from 'OutboundConnection [peerAddress=[8000], keyId=32603e73-0f2f-466d-9e51-177aa2438e69]' 
11:51:13.454 DEBUG [Connection.read-[60181]-8ac7fb69] b.n.p.n.Connection: Received message: PeerExchangeResponse(nonce=870776773, peers=[]) at: 'OutboundConnection [peerAddress=[60181], keyId=8ac7fb69-8036-4a18-903c-b68131711d8f]' 
11:51:13.454 DEBUG [NetworkService.dispatcher-0] b.n.p.n.a.t.h.HashCashTokenService: isDifficultyInvalid/currentNetworkLoad: message.getCostFactor()=0.1, networkLoad.getValue()=0.009263141333333334 
11:51:13.455 INFO  [NetworkService.dispatcher-0] b.n.p.s.p.e.PeerExchangeRequestHandler: Node with address [54223] received PeerExchangeResponse from [60181] with 0 peers 
11:51:13.455 INFO  [NetworkService.network-IO-pool-10] b.n.p.s.p.e.PeerExchangeService: Node with address [54223] completed peer exchange with [60181] and received 0 reportedPeers. 
11:51:13.455 INFO  [NetworkService.network-IO-pool-10] b.n.p.s.p.e.PeerExchangeService: We got at least one peerExchange future completed. 
11:51:13.468 DEBUG [Connection.read-[8000]-32603e73] b.n.p.n.Connection: Received message: PeerExchangeResponse(nonce=-974233054, peers=[Peer(address=[60181], capability=Capability(address=[60181], supportedTransportTypes=[CLEAR], features=[INVENTORY_HASH_SET, AUTHORIZATION_HASH_CASH]), ... at: 'OutboundConnection [peerAddress=[8000], keyId=32603e73-0f2f-466d-9e51-177aa2438e69]' 
11:51:13.469 DEBUG [NetworkService.dispatcher-0] b.n.p.n.a.t.h.HashCashTokenService: isDifficultyInvalid/currentNetworkLoad: message.getCostFactor()=0.1, networkLoad.getValue()=0.009263141333333334 
11:51:13.469 INFO  [NetworkService.dispatcher-0] b.n.p.s.p.e.PeerExchangeRequestHandler: Node with address [54223] received PeerExchangeResponse from [8000] with 1 peers 
11:51:13.469 INFO  [NetworkService.network-IO-pool-8] b.n.p.s.p.e.PeerExchangeService: Node with address [54223] completed peer exchange with [8000] and received 1 reportedPeers. 
11:51:13.469 INFO  [NetworkService.network-IO-pool-8] b.n.p.s.p.e.PeerExchangeService: Node with address [54223] completed peer exchange to 3 candidates. 2 requests successfully completed. 
11:51:13.470 INFO  [NetworkService.network-IO-pool-8] b.n.p.s.p.e.PeerExchangeService: Node with address [54223] repeats the initial peer exchange after 16 sec as it has not reached sufficient connections or received sufficient peers 
```

I just debugged into it. It fails because the price that is set by default and formatted to DE_de locale ("61825,41") is not a Double (Fails in PriceValidator line:35). The validation isn't handling localization of numbers properly ATM.

**Comment by HenrikJannsen** [comment]
@ripcurlx Do you use latest main or live data? There was an issue with the Market object and no price available which is resolved but with live data you still get the invalid market data thus leading to an exception.

**Comment by ripcurlx** [comment]
I can still reproduce it every time on the current main branch.

**Comment by HenrikJannsen** [comment]
I could reproduce it when entering a `,` instead of a '.' for decimal separator. 

I think we should avoid all that number format mess. The local standards are very bad from readability and the mix of comma and dot is a risk for making mistakes when ppl are used to english format and then get confronted with their local.

See https://github.com/bisq-network/bisq2/issues/2036
