### ISSUE TITLE
Upgrade to 2.0.2 is looking for incorrect file name

### ISSUE THREAD

**Issue by acarlton** [bisq-network/bisq2#1982]
Seems that two files have the wrong filename when trying to download the latest release from inside the app.

![Screenshot from 2024-04-03 13-42-37](https://github.com/bisq-network/bisq2/assets/17485/086f3f14-3763-4391-9e7b-66f8522a5c2c)

**Comment by muninnnnnn** [comment]
I have the same problem and getting this error on Windows 7 Ultimate.

java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 400 for URL: https://github.com/bisq-network/bisq2/releases/download/v2.0.2/Bisq 2-2.0.2.exe.asc
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeExce...

**Comment by HenrikJannsen** [comment]
It's a know issue and resolved for next release. Can you please update manually at https://github.com/bisq-network/bisq2/releases/v2.0.2
