### ISSUE TITLE
Java fail order

### ISSUE THREAD

**Issue by covillano** [bisq-network/bisq2#1985]
When I try to make a purchase I get this error.

![imagen](https://github.com/bisq-network/bisq2/assets/166005836/bcb71dc1-ca66-46ea-8603-70e158dd176f)

**Comment by covillano** [comment]
java.lang.NullPointerException: Cannot invoke "bisq.common.monetary.Monetary.getValue()" because "baseSideAmount" is null
	at bisq.trade.bisq_easy.BisqEasyTradeService.createBisqEasyProtocol(BisqEasyTradeService.java:188)
	at bisq.desktop.main.content.bisq_easy.take_offer.review.TakeOfferReviewController.doTakeOffer(TakeOfferReviewController.java:216)
	at bisq.desktop.main.content.bisq_easy.take_offer.review.TakeOfferReviewController.takeOffer(TakeOfferReviewController.java:205)
	at bisq.desktop.main.content.bisq_easy.take_offer.TakeOfferController.onTakeOffer(TakeOfferController.java:251)
	at bisq.desktop.main.content.bisq_easy.take_offer.TakeOfferView.lambda$onViewAttached$7(TakeOfferView.java:203)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEve...
