### ISSUE TITLE
FsmException  in BisqEasyTakeOfferRequestHandler.verifyMessage

### ISSUE THREAD

**Issue by threehill** [bisq-network/bisq2#1996]
The peer's trade failed due an error.
Error caused by: NoSuchElementException, FsmException

Stack trace: java.util.NoSuchElementException
    at java.base/java.util.Optional.orElseThrow(Optional.java:377)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.verifyMessage(BisqEasyTakeOfferRequestHandler.java:101)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.handle(BisqEasyTakeOfferRequestHandler.java:53)
    at bisq.common.fsm.Fsm.handle(Fsm.java:83)
    at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
   ...

**Comment by threehill** [comment]
Also: "Sending message failed"

**Comment by HenrikJannsen** [comment]
It seems that happened because of network issues. That the offer the taker took was not found on your node. Or that the data in the offer has be altered by recent changes (not aware which one but cannot exclude that). I added more detail logs if it appears again.
