### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sroo8** [bisq-network/bisq2#2249]
Long time Bisq 1 user. First time using Bisq 2 and I get multiple pop-up error messages for java.lang.ArrayIndexOutOfBoundsException.

![image](https://github.com/bisq-network/bisq2/assets/147955891/ee95476b-57b7-425a-a075-54ee864f7eb0)

![image](https://github.com/bisq-network/bisq2/assets/147955891/205abdc8-dbbe-466c-b133-176954c1420f)

**Comment by HenrikJannsen** [comment]
Do you run version 2.0.4? Can you post the log file?

**Comment by sroo8** [comment]
Is there any sensitive information in the log file?

**Comment by sroo8** [comment]
Yes running 2.0.4. Downloaded it about 10 minutes before posting the errors.

**Comment by sroo8** [comment]
Here's a portion of the log file.

`Received 1999.955 KB of inventory data from: [REDACTED].onion:2842 after 60.69 sec.; 
Still missing data. Response got truncated because max size was reached
##########################################################################################
  18 item(s) of AddAuthenticatedDataRequest.AuthorizedBondedRole
   2 item(s) of AddAuthenticatedDataRequest.AuthorizedDifficultyAdjustmentData
2116 item(s) of AddAuthenticatedDataRequest.AuthorizedTimestampData
 310 item(s) of AddAuthenticatedDataRequest.AuthorizedProofOfBurnData
1165 item(s) of AddAuthenticatedDataRequest.UserProfile
   1 item(s) of AddAuthenticatedDataRequest.ReleaseNotification
 162 item(s) of AddAuthenticatedDataRequest.AuthorizedSignedWitnessData
  23 item(s) of AddAuthenticatedDataRequest.AuthorizedBondedReputationData
 219 item(s) of AddAuthenticatedDataRequest.AuthorizedAccountAgeData
   2 item(s) of AddAuthenticatedDataRequest.AuthorizedOracleNode
########################################################################################## 
Jun-03 14:17:58.046 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 191 out of bounds for length 191
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.047 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.047 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 191 out of bounds for length 191
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.101 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 269 out of bounds for length 269
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.102 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.102 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 269 out of bounds for length 269
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.203 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 394 out of bounds for length 394
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.204 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.204 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 394 out of bounds for length 394
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.229 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 422 out of bounds for length 422
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.229 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.229 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 422 out of bounds for length 422
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.248 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 444 out of bounds for length 444
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.248 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.248 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 444 out of bounds for length 444
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.277 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 472 out of bounds for length 472
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.277 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.277 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 472 out of bounds for length 472
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.307 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 503 out of bounds for length 503
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.308 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.308 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: Index 503 out of bounds for length 503
	at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
	at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at bisq.user.profile.UserProfileService.getUserProfiles(UserProfileService.java:104)
	at bisq.desktop.main.content.dashboard.DashboardController.lambda$onActivate$1(DashboardController.java:68)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jun-03 14:17:58.364 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.364 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.365 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.580 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.580 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.580 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.596 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.596 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.596 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.616 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.616 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.616 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.632 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.632 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.632 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.670 [JavaFX Application Thread] ERROR b.d.DesktopExecutable: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null

Jun-03 14:17:58.670 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception from thread Thread[JavaFX Application Thread,5,main] 
Jun-03 14:17:58.670 [JavaFX Application Thread] ERROR b.d.DesktopController: Uncaught exception: java.lang.ArrayIndexOutOfBoundsException: null
`

**Comment by kciouv** [comment]
Assuming you're on Linux, what does this return?

```
grep VERSION $JAVA_HOME/release 
```

At the moment, the targeted version of Java to run Bisq2 is 17; without any more context, I'm inclined to think that your distribution isn't packaging it correctly.

**Comment by sroo8** [comment]
If I run "java -version" I get: 
```
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-122.04, mixed mode, sharing)
```

**Comment by HenrikJannsen** [comment]
If you have not any user data already, could you try to delete the data directory and start over again? I never saw that exception, might be caused by corrupted persistence data.
If you had already custom user data, can you go into the data directory and delete the `network_db` folder and the `user_profile_store.protobuf` file under `settings`?

**Comment by sroo8** [comment]
It happened right after installing. The first time I started Bisq 2.

**Comment by Lagrang3** [comment]
Same issue for me.

**Comment by HenrikJannsen** [comment]
@Lagrang3 @sroo8 Do you still have that issue with 2.0.4?

**Comment by sroo8** [comment]
> @Lagrang3 @sroo8 Do you still have that issue with 2.0.4?

I haven't been using v2.

**Comment by HenrikJannsen** [comment]
I will close as long its not happening again.

**Comment by iUnstable0** [comment]
It indeed is still happening, inf act, its happening on both Bisq1 and Bisq2 gui. This issue is very annoying and it happened right after I installed bisq on my mac
