### ISSUE TITLE
Bisq Easy: Seeing an Open Trade for an Offer that I never made!  Error message follow

### ISSUE THREAD

**Issue by cparke2** [bisq-network/bisq2#2392]
I haven't opened Bisq2 in a few days.  When I opened it today, I see Open Trade  ID 5732f636-7002-313f-bed6-e134f417582e that I never opened, in which I am listed as the Maker to Buy 0.00082854 BTC for 50.00 by US Money Order.  **The trade is not valid**, however, and when I click I on it, the error message appears:

"The trade failed with error message: Could not find matching offer in BisqEasyOfferbookChannel"

Stack trace: java.lang.RuntimeException: Could not find matching offer in BisqEasyOfferbookChannel
	at bisq.common.fsm.Fsm.handle(Fsm.java:114)
	at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
	at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeService.java:259)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onBisqEasyTakeOfferMessage(BisqEasyTradeService.java:134)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onMessage(BisqEasyTradeService.java:109)
	at bisq.network.p2p.services.confidential.ConfidentialMessageService.lambda$processConfidentialMessage$8(ConfidentialMessageService.java:298)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.services.confidential.ConfidentialMessageService.lambda$processConfidentialMessage$9(ConfidentialMessageService.java:296)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

Not sure why this happened to me or how to clear it out of my system.  It is mostly a nuisance but reporting it anyway because this sort of thing isn't supposed to happen!

Full Log of the incident of trying to open this phantom trade:

Jul-10 21:37:23.666 [NetworkService.dispatcher-0] INFO  b.c.fsm.Fsm: Handle BisqEasyAccountDataMessage at BisqEasyAccountDataMessageHandler 
Jul-10 21:37:23.672 [NetworkService.dispatcher-0] INFO  b.c.fsm.Fsm: Transition completed to new state BisqEasyTradeState.MAKER_DID_NOT_SENT_TAKE_OFFER_RESPONSE__BUYER_DID_NOT_SENT_BTC_ADDRESS__BUYER_RECEIVED_ACCOUNT_DATA(isFinalState=false, ordinal=23) 
Jul-10 21:37:23.685 [NetworkService.dispatcher-0] INFO  b.n.p.s.c.a.MessageDeliveryStatusService: Received a BisqEasyTakeOfferRequest with message ID 94450fa3-0609-47ea-b7d6-8a1568d1aba6 
Jul-10 21:37:23.686 [NetworkService.dispatcher-0] INFO  b.c.fsm.Fsm: Start transition from currentState BisqEasyTradeState.MAKER_DID_NOT_SENT_TAKE_OFFER_RESPONSE__BUYER_DID_NOT_SENT_BTC_ADDRESS__BUYER_RECEIVED_ACCOUNT_DATA(isFinalState=false, ordinal=23) 
Jul-10 21:37:23.718 [NetworkService.network-IO-pool-23] INFO  b.n.p.n.t.TorTransportService: Start creating tor socket to ojkstx6wjsefibhaahvdqbmmqq3kgsltnjp5zjsajzr22v64wawmalid.onion:45365 
Jul-10 21:37:23.768 [NetworkService.dispatcher-0] INFO  b.c.fsm.Fsm: Handle BisqEasyTakeOfferRequest at BisqEasyTakeOfferRequestHandler 
Jul-10 21:37:23.777 [NetworkService.dispatcher-0] ERROR b.t.b.p.m.BisqEasyTakeOfferRequestHandler: Could not find matching offer in BisqEasyOfferbookChannel.
takersOffer=BisqEasyOffer(super=Offer(id=3cef52d9-0ff7-4cff-b66b-99dea01917c2, date=1719722062552, makerNetworkId=NetworkId(addressByTransportTypeMap=AddressByTransportTypeMap(map={TOR=6obmmgpd7n7otj756bk7hrcrgacyys3rrbyylrpfxxrgj54mcnflltad.onion:48698}), pubKey=PubKey(keyId=89e98f147eb902aa17b23a6b02b70b194d695426, id=0b5b9a96ccbaa28c0089a057eaeb10d097f22919)), direction=BUY, market=US Dollar (BTC/USD), amountSpec=QuoteSideFixedAmountSpec(super=FixedAmountSpec(amount=499997)), priceSpec=FloatPriceSpec(percentage=0.0795), protocolTypes=[BISQ_EASY], baseSidePaymentMethodSpecs=[BitcoinPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=BitcoinPaymentMethod(super=PaymentMethod(name=MAIN_CHAIN, paymentRail=MAIN_CHAIN, displayString=MAIN_CHAIN, shortDisplayString=MAIN_CHAIN))))], quoteSidePaymentMethodSpecs=[FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=CASH_DEPOSIT, paymentRail=CASH_DEPOSIT, displayString=Cash Deposit, shortDisplayString=Cash Deposit)))), FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=US_POSTAL_MONEY_ORDER, paymentRail=US_POSTAL_MONEY_ORDER, displayString=US Postal Money Order, shortDisplayString=US Money Order)))), FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=Chime, paymentRail=CUSTOM, displayString=Chime, shortDisplayString=Chime)))), FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=ZELLE, paymentRail=ZELLE, displayString=Zelle, shortDisplayString=Zelle))))], offerOptions=[ReputationOption(requiredTotalReputationScore=10000)]), supportedLanguageCodes=[en])

Jul-10 21:37:23.779 [NetworkService.dispatcher-0] ERROR b.c.fsm.Fsm: Error at handling BisqEasyTakeOfferRequest(super=BisqEasyTradeMessage(super=TradeMessage(id=94450fa3-0609-47ea-b7d6-8a1568d1aba6, tradeId=5732f636-7002-313f-bed6-e134f417582e, protocolVersion=1.0.0, sender=NetworkId(addressByTransportTypeMap=AddressByTransportTypeMap(map={TOR=ojkstx6wjsefibhaahvdqbmmqq3kgsltnjp5zjsajzr22v64wawmalid.onion:45365}), pubKey=PubKey(keyId=bc3ed7e3238c2b51db9ce22bf8177d2e4535abc6, id=eec36e3be3b4071c2a63ef1cff0cc93f622a2057)), receiver=NetworkId(addressByTransportTypeMap=AddressByTransportTypeMap(map={TOR=6obmmgpd7n7otj756bk7hrcrgacyys3rrbyylrpfxxrgj54mcnflltad.onion:48698}), pubKey=PubKey(keyId=89e98f147eb902aa17b23a6b02b70b194d695426, id=0b5b9a96ccbaa28c0089a057eaeb10d097f22919))), metaData=MetaData(ttl=864000000, priority=1, className=BisqEasyTakeOfferRequest, maxMapSize=1000)), bisqEasyContract=BisqEasyContract(super=TwoPartyContract(super=Contract(takeOfferDate=1720449036371, offer=BisqEasyOffer(super=Offer(id=3cef52d9-0ff7-4cff-b66b-99dea01917c2, date=1719722062552, makerNetworkId=NetworkId(addressByTransportTypeMap=AddressByTransportTypeMap(map={TOR=6obmmgpd7n7otj756bk7hrcrgacyys3rrbyylrpfxxrgj54mcnflltad.onion:48698}), pubKey=PubKey(keyId=89e98f147eb902aa17b23a6b02b70b194d695426, id=0b5b9a96ccbaa28c0089a057eaeb10d097f22919)), direction=BUY, market=US Dollar (BTC/USD), amountSpec=QuoteSideFixedAmountSpec(super=FixedAmountSpec(amount=499997)), priceSpec=FloatPriceSpec(percentage=0.0795), protocolTypes=[BISQ_EASY], baseSidePaymentMethodSpecs=[BitcoinPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=BitcoinPaymentMethod(super=PaymentMethod(name=MAIN_CHAIN, paymentRail=MAIN_CHAIN, displayString=MAIN_CHAIN, shortDisplayString=MAIN_CHAIN))))], quoteSidePaymentMethodSpecs=[FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=CASH_DEPOSIT, paymentRail=CASH_DEPOSIT, displayString=Cash Deposit, shortDisplayString=Cash Deposit)))), FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=US_POSTAL_MONEY_ORDER, paymentRail=US_POSTAL_MONEY_ORDER, displayString=US Postal Money Order, shortDisplayString=US Money Order)))), FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=Chime, paymentRail=CUSTOM, displayString=Chime, shortDisplayString=Chime)))), FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=ZELLE, paymentRail=ZELLE, displayString=Zelle, shortDisplayString=Zelle))))], offerOptions=[ReputationOption(requiredTotalReputationScore=10000)]), supportedLanguageCodes=[en]), protocolType=BISQ_EASY, maker=Party(role=MAKER, networkId=NetworkId(addressByTransportTypeMap=AddressByTransportTypeMap(map={TOR=6obmmgpd7n7otj756bk7hrcrgacyys3rrbyylrpfxxrgj54mcnflltad.onion:48698}), pubKey=PubKey(keyId=89e98f147eb902aa17b23a6b02b70b194d695426, id=0b5b9a96ccbaa28c0089a057eaeb10d097f22919)))), taker=Party(role=TAKER, networkId=NetworkId(addressByTransportTypeMap=AddressByTransportTypeMap(map={TOR=ojkstx6wjsefibhaahvdqbmmqq3kgsltnjp5zjsajzr22v64wawmalid.onion:45365}), pubKey=PubKey(keyId=bc3ed7e3238c2b51db9ce22bf8177d2e4535abc6, id=eec36e3be3b4071c2a63ef1cff0cc93f622a2057)))), baseSideAmount=82854, quoteSideAmount=499997, baseSidePaymentMethodSpec=BitcoinPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=BitcoinPaymentMethod(super=PaymentMethod(name=MAIN_CHAIN, paymentRail=MAIN_CHAIN, displayString=MAIN_CHAIN, shortDisplayString=MAIN_CHAIN)))), quoteSidePaymentMethodSpec=FiatPaymentMethodSpec(super=PaymentMethodSpec(saltedMakerAccountId=Optional.empty, paymentMethod=FiatPaymentMethod(super=PaymentMethod(name=US_POSTAL_MONEY_ORDER, paymentRail=US_POSTAL_MONEY_ORDER, displayString=US Postal Money Order, shortDisplayString=US Money Order)))), mediator=Optional[UserProfile{
                    nickName='solomon1923',
                    proofOfWork=ProofOfWork{
duration=29
difficulty=2^16.0 = 65536.0
counter=57121
challenge=null
solution=000000000000df21
payload=ea53d552ca83715ae623a9af52612190e0eb9961},
                    avatarVersion=0,
                    networkId=NetworkId(addressByTransportTypeMap=AddressByTransportTypeMap(map={TOR=3fatfssmx5h4tx4vqoty6t3skqqg33djkibs3jmyf6fqlsmwzjjhluqd.onion:19610}), pubKey=PubKey(keyId=2a7167016b44ae3304a25eb1ea772ce4d16df6ad, id=ea53d552ca83715ae623a9af52612190e0eb9961)),
                    terms='',
                    statement='Mediator',
                    nym='null',
                    proofOfBurnHash=null,
                    bondedReputationHash=null
}], agreedPriceSpec=FloatPriceSpec(percentage=0.0795), marketPrice=559026839, takeOfferDate=1720449036371), contractSignatureData=ContractSignatureData{
     contractHash=6fa96ff63a69e9745550beba9bc0d70b2efc1b6a,
     signature=304502203cbd382dd54a2b55ad7b565dca8374b37fa3ba409302b41fd95bfcdf713a0f94022100e60232edf82082a85d0d8c6758ad6dbf8562e218820b393a88a24390d3f356bc,
     publicKey=EC Public Key [cd:22:49:6c:27:96:5b:6b:cd:3e:71:4c:ff:05:6d:12:cb:0f:5b:5c]
            X: 54023d9f6003c85c04a2302076ead08788f714ba76e26790f0283ae66b15afeb
            Y: a710fb36f683162c544befb6863c3d0badf4032351b81d2f8b312a6fc3780aee

}). java.lang.RuntimeException: Could not find matching offer in BisqEasyOfferbookChannel
	at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.verifyMessage(BisqEasyTakeOfferRequestHandler.java:117)
	at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.handle(BisqEasyTakeOfferRequestHandler.java:59)
	at bisq.common.fsm.Fsm.handle(Fsm.java:83)
	at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
	at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeService.java:259)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onBisqEasyTakeOfferMessage(BisqEasyTradeService.java:134)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onMessage(BisqEasyTradeService.java:109)
	at bisq.network.p2p.services.confidential.ConfidentialMessageService.lambda$processConfidentialMessage$8(ConfidentialMessageService.java:298)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.services.confidential.ConfidentialMessageService.lambda$processConfidentialMessage$9(ConfidentialMessageService.java:296)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

Jul-10 21:37:23.786 [NetworkService.dispatcher-0] INFO  b.c.fsm.Fsm: Start transition from currentState BisqEasyTradeState.MAKER_DID_NOT_SENT_TAKE_OFFER_RESPONSE__BUYER_DID_NOT_SENT_BTC_ADDRESS__BUYER_RECEIVED_ACCOUNT_DATA(isFinalState=false, ordinal=23) 
Jul-10 21:37:23.788 [NetworkService.dispatcher-0] INFO  b.c.fsm.Fsm: Handle FsmErrorEvent at BisqEasyFsmErrorEventHandler 
Jul-10 21:37:23.796 [NetworkService.dispatcher-0] WARN  b.t.b.p.e.BisqEasyFsmErrorEventHandler: We send the cause stack and stackTrace to our peer.
errorMessage=RuntimeException, FsmException
stackTrace=java.lang.RuntimeException
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.verifyMessage(BisqEasyTakeOfferRequestHandler.java:117)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.handle(BisqEasyTakeOfferRequestHandler.java:59)
    at bisq.common.fsm.Fsm.handle(Fsm.java:83)
    at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
    at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeService.java:259)
    at bisq.trade.bisq_easy.BisqEasyTradeService.onBisqEasyTakeOfferMessage(BisqEasyTradeService.java:134)
    at bisq.trade.bisq_easy.BisqEasyTradeService.onMessage(BisqEasyTradeService.java:109)
    at bisq.network.p2p.services.confidential.ConfidentialMessageService.lambda$processConfidentialMessage$8(ConfidentialMessageService.java:298)
    at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
    at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
    at bisq.network.p2p.services.confidential.ConfidentialMessageService.lambda$processConfidentialMessage$9(ConfidentialMessageService.java:296)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by HenrikJannsen** [comment]
This is weird. Did you use multiple application directories or different computers? Are you 100% sure that this trade was not initiated by you?

**Comment by cparke2** [comment]
Yes, it is weird. No multiple directories or computers.  All I can say is that I did complete a previous trade with the same user, but haven't exited the completed trade.  Not sure what that has to do with anything, but just throwing it out there.  Honestly, I get a sense I am not the only one who has seen phantom trades like this, as there is another user I traded with who also was asking if I opened or completed trade that I had not.  It looks like I can close the phantom trade and make it disappear, though I've been keeping it open as evidence in case someone there wants to look into this further.

**Comment by HenrikJannsen** [comment]
Thanks for the background info. I see you have been the maker of the trade? Did you change the preferences to leave the offer online after one has taken it?
It might be that your closed the offer after one took it, but at roughly the same time another user tried to take it, but as the offer was removed at your local node it throws that exception. It might be that the remove message did not arrive at another peer, so there could be a longer time delay...

**Comment by cparke2** [comment]
The previous trade, I was the taker with the other party.  This phantom trade, I am listed as the maker, but I never listed such an offer!  The amounts are also different.  The offer, however, matches a different one made by the other party.  I know that sounds a bit confusing, but this whole thing is.  So no, I don't think it is a timing issue, but there is some evidence that some wires are got crossed in the system.

**Comment by HenrikJannsen** [comment]
Should be fixed with version 2.1.0 (https://github.com/bisq-network/bisq2/releases/tag/v2.1.0)
