### ISSUE TITLE
v2.0.5: Clicking on Lightning QR-Code button fails to open Webcam

### ISSUE THREAD

**Issue by hiciefte** [bisq-network/bisq2#2452]
When trying to open the LN QR-Code it closes immediately the connection window because of following error

```
11:40:10.020 ERROR [WebcamProcessLauncher-0] b.d.w.WebcamProcessLauncher: Launching process failed java.io.IOException: Could not load webcam-app/version.txt
	at bisq.common.util.FileUtils.getResourceAsStream(FileUtils.java:222)
	at bisq.common.util.FileUtils.readStringFromResource(FileUtils.java:203)
	at bisq.desktop.webcam.WebcamProcessLauncher.lambda$start$0(WebcamProcessLauncher.java:48)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

```

**Comment by HenrikJannsen** [comment]
Have you followed the build steps in the readme in the webcam module? There will be a webcam dir with a jar and version file inside after clicking the button if all is setup correctly.
