### ISSUE TITLE
v2.0.5: Scrollbar TimeoutException

### ISSUE THREAD

**Issue by hiciefte** [bisq-network/bisq2#2456]
I do see it on live nearly all the time, where it also takes some time to render the offerbogk. Now I also recognized it locally on Regtest. I got it in combination with a chat notification that somehow rendered in the notifications to "|". Not sure if it has something to do with this.

![Bildschirmfoto 2024-07-22 um 12 10 13](https://github.com/user-attachments/assets/c362d2cd-dc50-4987-8eee-10465b789b69)

**Comment by HenrikJannsen** [comment]
What is the exception?

**Comment by hiciefte** [comment]
sorry - completely missed to copy it to the issue 

```
10:25:23.322 ERROR [CompletableFutureDelayScheduler] b.d.m.c.c.m.l.ChatMessagesListView: Find scrollbar failed java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by HenrikJannsen** [comment]
Do you know how to reproduce that?

**Comment by HenrikJannsen** [comment]
If it still happens please re-open.
