### ISSUE TITLE
The peer's trade failed due an error.

### ISSUE THREAD

**Issue by igorbastosib** [bisq-network/bisq2#2738]
I saw few of this same error, all related with size of my LN invoice. The point is:
I'm using BISQ2 v2.1.0
As far as I read, this issue caused by size of LN invoice, was fixed on v2.0.2 or so.

Another thing is:
After this issue, all reputations went down several numbers.
A seller that had around 70k now is showing 19k.

Context:
I created an buying order with the seller on Saturday
Selected LN
Put my hash invoice (total of 402 characters)
When I opened my PC again on Monday I got the error and all reputations went down.

`Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: win / x86_64 / 64 v.10.0
Error message:
The peer's trade failed due an error.
Error caused by: RuntimeException, FsmException

Stack trace: java.lang.RuntimeException
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.verifyMessage(BisqEasyTakeOfferRequestHandler.java:116)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.handle(BisqEasyTakeOfferRequestHandler.java:58)
    at bisq.common.fsm.Fsm.handle(Fsm.java:83)
    at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
    at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeSe...`

**Comment by HenrikJannsen** [comment]
Could you upload the log file?
It seems your app have purged the outdated data but not received the updated re-fresh data yet, thus the reputation score dropped. 
The failure in the trade seems to be caused that either the offer message and trade data is not present. Have that trade been in a correct state before?
Did you have network connectivity issues? In the left bottom you see the number of peers which should be around 10 and while loading data you see an orange "loading network data" indicator, during that time its better to not trade as you might miss still data.

**Comment by HenrikJannsen** [comment]
Probably the issue which gets handled in https://github.com/bisq-network/bisq2/issues/3209
