### ISSUE TITLE
Error when trying to update from v2.0.2 to v2.1.0

### ISSUE THREAD

**Issue by dialup22** [bisq-network/bisq2#2784]
Hello. 

I'm currently on v2.0.2 of bisq2, and buyers are not being notified of my buy requests; advised by seller that pre v2.1 there were a lot of message delivery bugs. When I try to download and verify v2.1 I get the error below, so following guidance to post it here. Will attach log file as well. 

I am non-technical, so I'm not sure where to go/what to do when the guidance says to delete or uninstall the old application but NOT the data directory - any advice welcomed! 
Thanks

[bisq.log 08092024.txt](https://github.com/user-attachments/files/16921698/bisq.log.08092024.txt)

java.util.concurrent.CompletionException: java.lang.RuntimeException: javax.net.ssl.SSLException: Tag mismatch!
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: Tag mismatch!
	at bisq.updater.UpdaterService.lambda$download$3(UpdaterServi...

**Comment by HenrikJannsen** [comment]
From 2.0.2 you need to download from the Github webpage (https://github.com/bisq-network/bisq2/releases) as download links have changed. At the GH page there are instructions how to manually verify the installer.

**Comment by dialup22** [comment]
Thanks HenrikJannsen, will do that.
