### ISSUE TITLE
java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by MPins** [bisq-network/bisq2#2832]
Although it seems that Bisq2 is working properly,   I'm receiving the following error during its operation.

Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: linux / x86_64 / 64 v.6.8.0-44-generic
Error message:
java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(SystemTray.java:180)
	at java.desktop/sun.awt.X11.XTrayIconPeer$4$1.run(XTrayIconPeer.java:223)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by CoderBoogs** [comment]
I am getting the same error. When booting up TOR it gets to 50% then this error pops up.

**Comment by HenrikJannsen** [comment]
Seems to be caused by Gnome 3.28:
https://stackoverflow.com/questions/50440268/the-system-tray-is-not-supported-on-the-current-platform/50574518#50574518
Also: https://bugs.openjdk.org/browse/JDK-8058804

In Bisq1 there the same issue reported and "mitigated" by suppressing the error popup. 
I will catch the exception and notifications will then be deactivated until a solution is found.

**Comment by VictorSesma** [comment]
I am getting the same error in Ubuntu 24.04.1 LTS with Wayland, NVIDIA GeForce RTX™ 3060 and Nvidia driver version 550.120. I think the only difference is the kernel:

```
Bisq version: Version: v2.1.2 / Commit hash: addaf760c
Operating system: linux / x86_64 / 64 v.6.8.0-51-generic
Error message:
java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
	at java.desktop/java.awt.SystemTray.getSystemTray(SystemTray.java:180)
	at java.desktop/sun.awt.X11.XTrayIconPeer$4$1.run(XTrayIconPeer.java:223)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by HenrikJannsen** [comment]
Can you post the logs? In the provided log I cannot see where it originates in the Bisq code. The only area where we use SystemTray is covered by a try/catch.

**Comment by VictorSesma** [comment]
Hello @HenrikJannsen , sorry I can't be more helpful right now, could you tell me what logs you need? where are they stored?

Cheers

Victor

**Comment by VictorSesma** [comment]
Okay, I spoke too fast. I found the logs at `~/.local/share/Bisq2`

Just find the log file attached. Hope it helps.

[bisq_1.log](https://github.com/user-attachments/files/18581230/bisq_1.log)

(lines 26669, 26692, 78655, 78678)

**Comment by HenrikJannsen** [comment]
With https://github.com/bisq-network/bisq2/pull/3152 the popup should not popup anymore and we only log the error.

It is unclear from where it gets called as the stacktrace does not expose the path to a Bisq source code caller.
If you are a developer and can run from source code you could check with a breakpoint if AwtNotificationService is created. It should not as that is only used for Windows. SystemTray is not used anywhere else...
