### ISSUE TITLE
Trade failed

### ISSUE THREAD

**Issue by MPins** [bisq-network/bisq2#2839]
Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: linux / x86_64 / 64 v.6.8.0-44-generic
Error message:
The trade failed due an error.
Error message: Could not find matching offer in BisqEasyOfferbookChannel

Stack trace: bisq.common.fsm.FsmException: java.lang.RuntimeException: Could not find matching offer in BisqEasyOfferbookChannel
	at bisq.common.fsm.Fsm.handle(Fsm.java:114)
	at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
	at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeService.java:314)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onBisqEasyTakeOfferMessage(BisqEasyTradeService.java:184)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onMessage(Bis...

**Comment by HenrikJannsen** [comment]
Can you post the full logs?

**Comment by MPins** [comment]
Posted the log files founded on bisq2 dir

**Comment by MPins** [comment]
> Can you post the full logs?

[bisq.log](https://github.com/user-attachments/files/17056291/bisq.log)
[bisq_1.log](https://github.com/user-attachments/files/17056292/bisq_1.log)

**Comment by MPins** [comment]
Just happened again

Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: linux / x86_64 / 64 v.6.8.0-45-generic
Error message:
The trade failed due an error.
Error message: Could not find matching offer in BisqEasyOfferbookChannel

Stack trace: bisq.common.fsm.FsmException: java.lang.RuntimeException: Could not find matching offer in BisqEasyOfferbookChannel
	at bisq.common.fsm.Fsm.handle(Fsm.java:114)
	at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
	at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeService.java:314)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onBisqEasyTakeOfferMessage(BisqEasyTradeService.java:184)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onMessage(Bis...
[bisq.log](https://github.com/user-attachments/files/17063369/bisq.log)

**Comment by HenrikJannsen** [comment]
Covered by https://github.com/bisq-network/bisq2/issues/3209
