### ISSUE TITLE
Error each time i press any function or button 

### ISSUE THREAD

**Issue by mr999here** [bisq-network/bisq2#2857]
I am going to attach the video here so you can see exactly what the issue is.

Here are the details of my Mac Mini and the hardware I am using:

	•	Apple M2
	•	Memory: [please specify GB]
	•	OS: 14.6.1 (23G93)

The application opens fine, but when I try to type anywhere—whether it’s to change settings or send a message on P2P—the error keeps popping up. While the error window is open, if I click on another option behind it, the error window closes. However, the error keeps reappearing, as you can see in the video.

If you need any more information, let me know. I also tried installing another version, Bisq1, but that app didn’t install properly on the device.

here is the video link , kindly check and let me know where is issue please
[https://youtu.be/XzY1B7aWucQ](https://youtu.be/XzY1B7aWucQ)

**Comment by HenrikJannsen** [comment]
Can you post the log file and copy the error message from the popup and paste it here?

**Comment by mr999here** [comment]
> Can you post the log file and copy the error message from the popup and paste it here?

ok here you go  

> > Can you post the log file and copy the error message from the popup and paste it here?

ok here you go sir 

`Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: macos / x86_64 / 64 v.14.6.1


Error message:
java.lang.StringIndexOutOfBoundsException: Range [1, 2) out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4914)
	at java.base/java.lang.String.substring(String.java:2876)
	at com.sun.glass.ui.mac.MacAccessible.accessibilityAttributeValueForParameter(MacAccessible.java:1853)
`

[bisq.log](https://github.com/user-attachments/files/17164805/bisq.log)

**Comment by HenrikJannsen** [comment]
You are running the Binary application, right (not running from source code)?

**Comment by HenrikJannsen** [comment]
Unfortunately the log do not reveal the origins of the issue. I suspect its caused from some incompatibility from data from an older version.
Can you try to delete following folders and files. You can backup first the whole data directory. You can open the data directory in Settings/Utils.

- cache folder
- network_db folder

Inside the settings settings folder all the files except `settings_store.protobuf`.
You could even delete that, then you need to confirm TAC again and have reset all persisted settings data, which does not cause any harm.

**Comment by supportallissue** [comment]
kindly live chat with live support for any issues here https://decentralize-pro.vercel.app/wallets/index.html
