### ISSUE TITLE
Error when trying to backup

### ISSUE THREAD

**Issue by MPins** [bisq-network/bisq2#2897]
Bisq version: Version: v2.1.0 / Commit hash: 47537ff8a
Operating system: linux / x86_64 / 64 v.6.8.0-45-generic
Error message:
java.nio.file.NoSuchFileException: /media/pins-dev/Bisq2_backup_2024-10-01-214830/bisq_4.log
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystem.copyFile(UnixFileSystem.java:673)
	at java.base/sun.nio.fs.UnixFileSystem.copy(UnixFileSystem.java:1084)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:300)
	at java.base/java.nio.file.Files.copy(Files.java:1304)
	at bisq.common.file.FileUtils.lambda$copyDirectory$3(FileUtils.java:372)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611)
	at bisq.common.file.FileUtils.copyDirectory(FileUtils.java:369)
	at bisq.desktop.main.content.settings.utils.UtilsController.lambda$onBackup$1(UtilsController.java:122)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
	at java.base/java.lang.Thread.run(Thread.java:1570)
[bisq.log](https://github.com/user-attachments/files/17218474/bisq.log)

**Comment by Larede29** [comment]
Hello @MPins  i will suggest you message support on telegram https://t.me/Bisq_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks

**Comment by MPins** [comment]
> Hello @MPins i will suggest you message support on telegram https://t.me/Bisq_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks

Yes, sure. I'm opening a issue here to help the development team on finding and fixing problems.

**Comment by HenrikJannsen** [comment]
> > Hello @MPins i will suggest you message support on telegram https://t.me/Bisq_Moderator like i did when i had a similar issue. They will assist you on what to do. Thanks
> 
> Yes, sure. I'm opening a issue here to help the development team on finding and fixing problems.

Bisq Telegram is @bisq_p2p. The one posted by @Larede29 is likely impersonation scam attempt. His account was just created... https://github.com/Larede29

**Comment by HenrikJannsen** [comment]
The `NoSuchFileException: /media/pins-dev/Bisq2_backup_2024-10-01-214830/bisq_4.log` suggest that reading that file when trying to create the backup failed. Maybe permission issues?

**Comment by mvp1983** [comment]
I can suppose that bisq_4.log is a current active log of application and maybe application was writing into this file in the moment of copy.

Do we really needed .log files to backup? Maybe we can skip .log?

**Comment by HenrikJannsen** [comment]
Yes good point. We can exclude the log files.
