### ISSUE TITLE
Could not find matching offer in BisqEasyOfferbookChannel

### ISSUE THREAD

**Issue by MPins** [bisq-network/bisq2#2981]
Bisq version: Version: v2.1.2 / Commit hash: addaf760c
Operating system: linux / x86_64 / 64 v.6.8.0-47-generic
Error message:
The trade failed due an error.
Error message: [bisq.log](https://github.com/user-attachments/files/17636016/bisq.log)

Stack trace: bisq.common.fsm.FsmException: java.lang.RuntimeException: Could not find matching offer in BisqEasyOfferbookChannel
	at bisq.common.fsm.Fsm.handle(Fsm.java:114)
	at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
	at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeService.java:312)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onBisqEasyTakeOfferMessage(BisqEasyTradeService.java:182)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onMessage(Bis...

**Comment by HenrikJannsen** [comment]
Covered by https://github.com/bisq-network/bisq2/issues/3209
