### ISSUE TITLE
Trade Failed - Illegal Argument Exception

### ISSUE THREAD

**Issue by repankon** [bisq-network/bisq2#2998]
Bisq version: Version: v2.1.2 / Commit hash: addaf760c
Operating system: win / x86_64 / 64 v.10.0
Error message:
The peer's trade failed due an error.
Error caused by: IllegalArgumentException, FsmException

Stack trace: java.lang.IllegalArgumentException
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.validateAmount(BisqEasyTakeOfferRequestHandler.java:211)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.verifyMessage(BisqEasyTakeOfferRequestHandler.java:121)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.handle(BisqEasyTakeOfferRequestHandler.java:58)
    at bisq.common.fsm.Fsm.handle(Fsm.java:83)
    at bisq.trade.bi...

**Comment by HenrikJannsen** [comment]
Probably same as https://github.com/bisq-network/bisq2/issues/2999

Close as expected in rare conditions. Thought the error message could be make more user friendly as covered in https://github.com/bisq-network/bisq2/issues/3170
