### ISSUE TITLE
Bitcoin amount is too high

### ISSUE THREAD

**Issue by paola666** [bisq-network/bisq2#2999]
Bisq version: Version: v2.1.2 / Commit hash: addaf760c
Operating system: linux / x86_64 / 64 v.6.8.0-109048-tuxedo
Error message:
The trade failed due an error.
Error message: Takers (buyers) Bitcoin amount is too high. This can be caused by differences in the 2 traders market price or by an attempt by the taker to manipulate the price.

Stack trace: bisq.common.fsm.FsmException: java.lang.IllegalArgumentException: Takers (buyers) Bitcoin amount is too high. This can be caused by differences in the 2 traders market price or by an attempt by the taker to manipulate the price.

	at bisq.common.fsm.Fsm.handle(Fsm.java:114)
	at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
	at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeService.java:312)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onB...

**Comment by HenrikJannsen** [comment]
This can happen if both traders had a market price which was too different (outside of a permitted tolerance).

**Comment by HenrikJannsen** [comment]
Close as expected in rare conditions. Thought the error message could be make more user friendly as covered in https://github.com/bisq-network/bisq2/issues/3170
