### ISSUE TITLE
start of bisq 2.1.2 always fails at 24% while connection to tor 

### ISSUE THREAD

**Issue by RichardGantz** [bisq-network/bisq2#3015]
A debug.log in the directory ~/.local/share/Bisq2/tor does NOT exist.
Installed is tor as a service:
```
● tor.service - Anonymizing overlay network for TCP (multi-instance-master)
     Loaded: loaded (/lib/systemd/system/tor.service; enabled; vendor preset: enabled)
     Active: active (exited) since Mon 2024-11-18 19:16:17 CET; 2min 47s ago
    Process: 15516 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 15516 (code=exited, status=0/SUCCESS)
```

I was asked to open a new issue and post this error message to the developers:
```
Bisq-Version: Version: v2.1.2 / Commit-Hash: addaf760c
Betriebssystem: linux / x86_64 / 64 v.5.4.0-193-generic
Fehlermeldung:
Ein Fehler ist beim Starten von Bisq aufgetreten: java.util.concurrent.TimeoutException.
```

UPDATE on the 21st of November, 2024:

Tried to install bisq2 on another machine with a slightly other linux mint, but with the same result:

"Initializing applicationService failed".

The error message window that should be posted says:

```
Bisq-Version: Version: v2.1.2 / Commit-Hash: addaf760c
Betriebssystem: linux / x86_64 / 64 v.5.4.0-196-generic
Fehlermeldung:
Ein Fehler ist beim Starten von Bisq aufgetreten: java.util.concurrent.TimeoutException.
```

[bisq.log](https://github.com/user-attachments/files/17843117/bisq.log)

Lines 277 to 287 of the attached ~/.local/share/Bisq2/bisq.log file state the timeout error:
```
Nov.-21 09:56:15.745 [CompletableFutureDelayScheduler] ERROR b.d.DesktopApplicationService: Initializing applicationService failed java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

Nov.-21 09:56:15.747 [CompletableFutureDelayScheduler] INFO  b.d.DesktopApplicationService: New state FAILED 
```
Lines 462 to 467 of the attached  of the ~/.local/share/Bisq2/bisq.log:

```
Nov.-21 10:00:53.482 [JavaFX Application Thread] INFO  b.c.p.PlatformUtils: Trying to exec: cmd = kde-open args = %s file = <HOME_DIR>/.local/share/Bisq2/bisq.log 
Nov.-21 10:00:53.485 [JavaFX Application Thread] WARN  b.c.p.PlatformUtils: Error running command. java.io.IOException: Cannot run program "kde-open": error=2, Datei oder Verzeichnis nicht gefunden 
Nov.-21 10:00:53.486 [JavaFX Application Thread] INFO  b.c.p.PlatformUtils: Trying to exec: cmd = gnome-open args = %s file = <HOME_DIR>/.local/share/Bisq2/bisq.log 
Nov.-21 10:00:53.488 [JavaFX Application Thread] WARN  b.c.p.PlatformUtils: Error running command. java.io.IOException: Cannot run program "gnome-open": error=2, Datei oder Verzeichnis nicht gefunden 
Nov.-21 10:00:53.489 [JavaFX Application Thread] INFO  b.c.p.PlatformUtils: Trying to exec: cmd = xdg-open args = %s file = <HOME_DIR>/.local/share/Bisq2/bisq.log 
Nov.-21 10:00:53.510 [JavaFX Application Thread] INFO  b.c.p.PlatformUtils: Process is running. 
```

**Comment by HenrikJannsen** [comment]
Have you tried to delete the tor directory in the Bisq 2 data directory?

**Comment by HenrikJannsen** [comment]
If you use Linux, you need to install Tor (should get installed if you use the Bisq installer).
`sudo apt-get install tor`

In 2.1.2 we added the tor dependency to the installer instead of shipping it with Bisq binary on Linux.

**Comment by HenrikJannsen** [comment]
With 2.1.7 we show a delete tor dir button after 2 min.
