### ISSUE TITLE
bisq2 error message

### ISSUE THREAD

**Issue by apd24** [bisq-network/bisq2#3020]
Versión de Bisq: Versión: v2.1.2 / Hash del commit: addaf760c
Sistema operativo: win / x86_64 / 64 v.10.0
Mensaje de error:
java.lang.IllegalArgumentException: Unmatched braces in the pattern.
	at java.base/java.text.MessageFormat.applyPatternImpl(MessageFormat.java:556)
	at java.base/java.text.MessageFormat.<init>(MessageFormat.java:383)
	at java.base/java.text.MessageFormat.format(MessageFormat.java:898)
	at bisq.i18n.Res.get(Res.java:67)
	at bisq.desktop.main.content.bisq_easy.BisqEasyServiceUtil.getFormattedPriceSpec(BisqEasyServiceUtil.java:120)
	at bisq.desktop.main.content.bisq_easy.BisqEasyServiceUtil.createBasicOfferBookMessage(BisqEasyServiceUtil.java:72)
	at bisq.desktop.main.content.chat.message_container.list.ChatMessageListItem.getLocalizedOfferBookMessage(ChatMessageListItem.java:320)
	at bisq.desktop.main.content.chat.message_container.list.ChatMessageListItem.<init>(ChatMessageListItem.java:161)
	at bisq.desktop.main.content.chat.message_container.list.ChatMessagesListController.lambda$bindChatMessages$32(ChatMessagesListController.java:636)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194)
	at java.base/java.util.concurrent.CopyOnWriteArrayList$COWIterator.forEachRemaining(CopyOnWriteArrayList.java:1236)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702)
	at bisq.desktop.main.content.chat.message_container.list.ChatMessagesListController.bindChatMessages(ChatMessagesListController.java:645)
	at bisq.desktop.main.content.chat.message_container.list.ChatMessagesListController.lambda$selectedChannelChanged$6(ChatMessagesListController.java:200)
	at bisq.desktop.common.threading.UIThread.run(UIThread.java:27)
	at bisq.desktop.main.content.chat.message_container.list.ChatMessagesListController.selectedChannelChanged(ChatMessagesListController.java:185)
	at bisq.common.observable.Observable.addObserver(Observable.java:42)
	at bisq.desktop.main.content.chat.message_container.list.ChatMessagesListController.onActivate(ChatMessagesListController.java:136)
	at bisq.desktop.common.view.Controller.onActivateInternal(Controller.java:31)
	at bisq.desktop.common.view.View.onViewAttachedPrivate(View.java:100)
	at bisq.desktop.common.view.View.handleSceneChange(View.java:55)
	at bisq.desktop.common.view.View.lambda$new$0(View.java:47)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1047)
	at javafx.scene.Node.invalidatedScenes(Node.java:1098)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent.scenesChanged(Parent.java:773)
	at javafx.scene.Node.invalidatedScenes(Node.java:1069)
	at javafx.scene.Node.setScenes(Node.java:1136)
	at javafx.scene.Parent$2.onChanged(Parent.java:373)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:44)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:327)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:71)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:246)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:210)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:200)
	at java.base/java.util.AbstractList.add(AbstractList.java:113)
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:212)
	at bisq.desktop.main.content.ContentView.lambda$new$0(ContentView.java:46)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at bisq.desktop.common.view.NavigationModel.setView(NavigationModel.java:55)
	at bisq.desktop.common.view.NavigationController.processNavigationTarget(NavigationController.java:54)
	at bisq.desktop.common.view.Navigation.lambda$navigateTo$1(Navigation.java:66)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.common.view.Navigation.lambda$navigateTo$2(Navigation.java:66)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1605)
	at bisq.desktop.common.view.Navigation.navigateTo(Navigation.java:64)
	at bisq.desktop.main.content.dashboard.DashboardController.onOpenBisqEasy(DashboardController.java:104)
	at bisq.desktop.main.content.dashboard.DashboardView.lambda$getBigWidgetBox$4(DashboardView.java:242)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8917)
	at javafx.scene.control.Button.fire(Button.java:203)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3985)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1891)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2709)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by Bryan1722-alt** [comment]
Hello @apd24  i will suggest you message support on telegram https://t.me/BisqModerator like i did when i had a similar issue. They will assist you on what to do. Thanks
