### ISSUE TITLE
Could not find matching offer in BisqEasyOfferbookChannel

### ISSUE THREAD

**Issue by super-e** [bisq-network/bisq2#3035]
Versione di Bisq: Versione: v2.1.2 / Commit hash: addaf760c
Sistema operativo: win / x86_64 / 64 v.10.0
Messaggio di errore:
La compravendita è fallita  a causa di un errore.
Messaggio di errore: Could not find matching offer in BisqEasyOfferbookChannel

Traccia dello stack: bisq.common.fsm.FsmException: java.lang.RuntimeException: Could not find matching offer in BisqEasyOfferbookChannel
	at bisq.common.fsm.Fsm.handle(Fsm.java:114)
	at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
	at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeService.java:312)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onBisqEasyTakeOfferMessage(BisqEasyTradeService.java:182)
	at bisq.trade.bisq_easy.BisqEasyTradeService.onMessag...
[bisq.zip](https://github.com/user-attachments/files/17956823/bisq.zip)

**Comment by nostrbuddha** [comment]
Having same issue.

Bisq version: v2.1.2

<img width="880" alt="Screenshot 2024-12-22 at 10 12 32 AM" src="https://github.com/user-attachments/assets/648df7e7-1a73-466f-8305-376bfa243a93" />

When it happened.
1. There were no active/open trades yesterday. But I had 3+ offers posted
2. Today, all the offers are taken. 2 of the trades are fine.
3. Getting this issue with the 3rd trade

I can share any more details, if required.

Logs:
[bisq2-logs.zip](https://github.com/user-attachments/files/18220776/bisq2-logs.zip)

**Comment by HenrikJannsen** [comment]
Handled by https://github.com/bisq-network/bisq2/issues/3209

**Comment by HenrikJannsen** [comment]
Looking closer into it...

There was a 2 take-offer attempts for the same offer from mailbox messages, thus they have been executed at nearly the smae time but as the offer got removed after the first take offer the latter failed.

This is an expected situation but it should not trigger a error popup.

OfferId=ae45faf2-e3f4-47b9-a956-e8c0ee3ecc8b

```
Dec-22 10:00:56.408 [Network.dispatcher-0] INFO  b.c.fsm.Fsm: Start transition from currentState BisqEasyTradeState.INIT(isFinalState=false, ordinal=0) 
Dec-22 10:00:56.423 [Network.dispatcher-0] INFO  b.c.fsm.Fsm: Handle BisqEasyTakeOfferRequest at BisqEasyTakeOfferRequestHandler 
Dec-22 10:00:56.445 [Network.dispatcher-0] INFO  b.t.b.p.m.BisqEasyTakeOfferRequestHandler: My amount and the amount set by the taker are not the same. This is expected if the offer used a market based price and the taker had a different market price.
takersAmount=111791
myAmount=112672
errorThreshold=118305.6
marketPrice=82178821790
priceQuote=88753127533
takersContract=BisqEasyContract(super=TwoPartyContract(super=Contract(takeOfferDate=1734813956808, offer=BisqEasyOffer(super=Offer(id=ae45faf2-e3f4-47b9-a956-e8c0ee3ecc8b, 
```
Taker: `spa4prirgfo4fgvzh2xiu43dvraemab555wmunab36zcknk5wtgtu2yd.onion:52721`

Offer got removed because it was taken:
```
Dec-22 10:00:56.542 [Network.dispatcher-0] INFO  b.t.b.p.m.BisqEasyTakeOfferRequestHandler: Offer with ID ae45faf2-e3f4-47b9-a956-e8c0ee3ecc8b removed 
```

``` 
Dec-22 10:00:56.616 [Network.dispatcher-0] ERROR b.t.b.p.m.BisqEasyTakeOfferRequestHandler: Could not find matching offer in BisqEasyOfferbookChannel.
takersOffer=BisqEasyOffer(super=Offer(id=ae45faf2-e3f4-47b9-a956-e8c0ee3ecc8b, date=1734751693472, 
```

Taker: `l7obqisdixarot3dkm4t7g4tnaq4iybk2gm5yrszoyixsdkridoyrnid.onion:62219`
