### ISSUE TITLE
TRADE FAILED Runtime/FSM Exception

### ISSUE THREAD

**Issue by YEGGO2025** [bisq-network/bisq2#3055]
Bisq version: Version: v2.1.2 / Commit hash: addaf760c
Operating system: win / x86_64 / 64 v.10.0
Error message:
The peer's trade failed due an error.
Error caused by: RuntimeException, FsmException

Stack trace: java.lang.RuntimeException
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.verifyMessage(BisqEasyTakeOfferRequestHandler.java:116)
    at bisq.trade.bisq_easy.protocol.messages.BisqEasyTakeOfferRequestHandler.handle(BisqEasyTakeOfferRequestHandler.java:58)
    at bisq.common.fsm.Fsm.handle(Fsm.java:83)
    at bisq.trade.bisq_easy.protocol.BisqEasyProtocol.handle(BisqEasyProtocol.java:49)
    at bisq.trade.bisq_easy.BisqEasyTradeService.handleEvent(BisqEasyTradeSe...
[bisq2-logs.zip](https://github.com/user-attachments/files/18141505/bisq2-logs.zip)
[bisq.log](https://github.com/user-attachments/files/18141506/bisq.log)

**Comment by HenrikJannsen** [comment]
The attached logs do not contain that exception. Maybe it it in another log file (bisq_2.log, bisq_3.log,...)

**Comment by YEGGO2025** [comment]
[bisq_1.log](https://github.com/user-attachments/files/18174565/bisq_1.log)
[bisq_2.log](https://github.com/user-attachments/files/18174566/bisq_2.log)
[bisq_3.log](https://github.com/user-attachments/files/18174567/bisq_3.log)
[bisq_4.log](https://github.com/user-attachments/files/18174568/bisq_4.log)
[bisq_5.log](https://github.com/user-attachments/files/18174569/bisq_5.log)
[bisq_6.log](https://github.com/user-attachments/files/18174571/bisq_6.log)
[bisq_7.log](https://github.com/user-attachments/files/18174572/bisq_7.log)
[bisq_8.log](https://github.com/user-attachments/files/18174573/bisq_8.log)
[bisq_9.log](https://github.com/user-attachments/files/18174574/bisq_9.log)

**Comment by YEGGO2025** [comment]
> The attached logs do not contain that exception. Maybe it it in another log file (bisq_2.log, bisq_3.log,...)

sorry, there i uploaded my next 9 logs, looking at the file date stamps it should be there.

**Comment by HenrikJannsen** [comment]
Found the exception there. The peer had an error as his offer was not found anymore in the channel.

**Comment by HenrikJannsen** [comment]
Handled by https://github.com/bisq-network/bisq2/issues/3170 and https://github.com/bisq-network/bisq2/issues/3209
